### ISSUE TITLE
Do you have any example ? real project how it works ? 

### ISSUE THREAD

**Issue by erenergul** [realrashid/sweet-alert#1]
I don't understand how to put my controller sweet alert function. I am using datatables yajra. I have deleted button. But I couldn't do it. and It made me really stupid. I use 
    @if (alert()->ready())
        <script>
            swal({
                title: "{!! alert()->message() !!}",
                type: "{!! alert()->type() !!}",
                text: "{!! alert()->option('text') !!}",
                showCancelButton: "{!! alert()->option('showCancelButton') !!}",
                cancelButtonColor: "{!! alert()->option('cancelButtonColor') !!}",
                confirmButtonColor: "{!! alert()->option('confirmButtonColor') !!}",
                confirmButtonText: "{!! alert()->option('confirmButtonText') !!}",
            }).then(function () {
                swal(
                    '{!! alert()->option('deleted') !!}',
                    '{!! alert()->option('msg') !!}',
                    '{!! alert()->option('type') !!}'
                )
            });
        </script>
    @endif
This part but Where should I put excatly ? Need to see sample and then I realize..

**Comment by realrashid** [comment]
its very easy you just need a jquery on click function.
ex:
in your controller method in my case its index method
```php
alert()->flash('Are you sure?', 'warning',[
        'text' => 'You won\'t be able to revert this!',
        'showCancelButton' => true,
        'confirmButtonColor' => '#3085d6',
        'cancelButtonColor' => '#d33',
        'confirmButtonText' => 'Yes, delete it!',
        // if user clicked Yes, delete it!
        // then this will run
        'deleted' => 'Deleted!',
        'msg' => 'Your file has been deleted.',
        'type' => 'success'
]);
```
in your view 
```javascript
<script>
       $("#delete").on('click', function(){
          swal({
             title: "{!! alert()->message() !!}",
             type: "{!! alert()->type() !!}",
             text: "{!! alert()->option('text') !!}",
             showCancelButton: "{!! alert()->option('showCancelButton') !!}",
             cancelButtonColor: "{!! alert()->option('cancelButtonColor') !!}",
             confirmButtonColor: "{!! alert()->option('confirmButtonColor') !!}",
             confirmButtonText: "{!! alert()->option('confirmButtonText') !!}",
           }).then(function () {
             swal(
                    '{!! alert()->option('deleted') !!}',
                    '{!! alert()->option('msg') !!}',
                    '{!! alert()->option('type') !!}'
                   )
         });
      });
</script>
```
no need this condition if you are using on-click method 
```php
@if (alert()->ready())
  
@endif
```

##Hope this will help !

##I will upload Demo Project Soon!

###Thanks
