### ISSUE TITLE
Class 'RealRashid\SweetAlert\Facades' not found

### ISSUE THREAD

**Issue by rahmatxfauzi** [realrashid/sweet-alert#10]
I dunno why when i call _use Alert;_ in my controller, then showing that error.
And i've add this to my configuration in  _config/app.php_
`'providers' => [`
 `.........................`
`RealRashid\SweetAlert\SweetAlertServiceProvider::class,`
`],`
`'aliases'=>[`
`...........................`
` 'Alert' => RealRashid\SweetAlert\Facades\Alert::class,`
`],`

**Comment by realrashid** [comment]
Run this command
``` bash
composer dumpautoload
```
And let me know it's resolve or not.
Also share your Laravel version.

**Comment by rahmatxfauzi** [comment]
Nothing gonna change when i run
```
composer dump-autoload
```
But when i add this into my controller, sweetalerts is work fine.
```
use RealRashid/SweetAlert/Facades/Alert;
```

I use laravel 5.6.32

**Comment by realrashid** [comment]
Thanks will add this in readme soon with new updates. 😎
