### ISSUE TITLE
Error When updating laravel 7 to 8

### ISSUE THREAD

**Issue by w99910** [realrashid/sweet-alert#100]
- Package Version: 3.1
- Laravel Version: 8.0

### Description: When Updating laravel 7 to 8 , realrashid/sweet-alert v3.1.6 requires laravel/framework ^5.4|^6.0|^7.0 -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8
.x-dev, 6.x-dev, 7.x-dev]

### Steps To Reproduce: 
![Screenshot (86)](https://user-images.githubusercontent.com/65523475/92456484-fe565980-f1e8-11ea-98b2-8f69a4651fec.png)

**Comment by realrashid** [comment]
Hey 👋,

You will soon get the support for Laravel 8😉.
