### ISSUE TITLE
Identical alarm is automatically triggered on an other page

### ISSUE THREAD

**Issue by nessor** [realrashid/sweet-alert#101]
- Package Version: 3.1.6
- Laravel Version: 7.25.0

### Description:
On other pages that implement an identical alert, it is triggered without action.

### Steps To Reproduce:

1. Side A implements Alert::info('header', 'body');
2. Page B also implements Alert::info('header','body');
3. Now an action is executed on page A to trigger the alert. E.g. the sending of a contact form. 
4. Directly after that, visit page B. The alarm appears immediately when the page is loaded without any user interaction.

**Edit:** 
Apparently the problem is not only with identical alerts.
Another example:

1. Page A implements Alert::info('foo', 'bar');
2. Side B does not implement an alert
3. Perform an action on page A so that the alarm is displayed.
4. Go to page B
5. Go to page A => Alarm appears again immediately without user interaction.

**Edit2:**
The "wrong" alert no longer appears if you reload the page once using F5. However, if a new alert is then triggered, it starts again from the beginning.

Is it possible that it might be a caching problem?

**Comment by realrashid** [comment]
Hey @nessor ,

Under the hood the package used Laravel Sesions.

Let me review the sesions again.

**Comment by nessor** [comment]
That's nice of you! Unfortunately I can't test changes anymore, because I can't use the package due to changes in the frontend :(

**Comment by realrashid** [comment]
Closed
