### ISSUE TITLE
Can't install on Laravel 8

### ISSUE THREAD

**Issue by kingRayhan** [realrashid/sweet-alert#103]
- Package Version: ^3.1
- Laravel Version: 8.x

### Description:
Can't install on laravel 8
![image](https://user-images.githubusercontent.com/7611746/92557365-e258c380-f28d-11ea-89dd-1768ffb2f149.png)

**Comment by Manzadey** [comment]
#102

**Comment by kingRayhan** [comment]
@Manzadey waiting for the merge :)
