### ISSUE TITLE
Not work on redirect back.

### ISSUE THREAD

**Issue by shankhadevpadam** [realrashid/sweet-alert#105]
- Package Version: 3.1.7
- Laravel Version: 7.28.3

### Description:
Alert not working, when using a redirect back.  Although I have configure middleware and .env settings.

```
SWEET_ALERT_MIDDLEWARE_AUTO_CLOSE=true
SWEET_ALERT_MIDDLEWARE_TOAST_POSITION=top-end
SWEET_ALERT_MIDDLEWARE_TOAST_CLOSE_BUTTON=false
SWEET_ALERT_AUTO_DISPLAY_ERROR_MESSAGES=true
SWEET_ALERT_MIDDLEWARE_ALERT_CLOSE_TIME=5000
```

```
return back()->withToastSuccess('Success Message');
```

### Steps To Reproduce:

**Comment by realrashid** [comment]
Hey @shankhadevpadam ,

Why not try with 
```php
return redirect()->back()->withToastSuccess('Task Created Successfully!');
```

Let me know if it's helpful 🙂

**Comment by shankhadevpadam** [comment]
I have already done this one also but not working.

**Comment by shankhadevpadam** [comment]
Fix my self. But one more question confirm before delete.

**Comment by realrashid** [comment]
Hey @shankhadevpadam ,
Sorry to inform you that I haven't added that functionality..
