### ISSUE TITLE
php 8 update issue

### ISSUE THREAD

**Issue by omaisali** [realrashid/sweet-alert#107]
- Package Version: 3.1.7
- Laravel Version: 8

### Description:
after setting php version to 8, there is an issue with sweet-alert

composer update 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires realrashid/sweet-alert ^3.1.7 -> satisfiable by realrashid/sweet-alert[v3.1.7].
    - realrashid/sweet-alert v3.1.7 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.

ANY HELP ?

**Comment by realrashid** [comment]
Hey 👋,

You will get php 8 support very soon..👍

**Comment by realrashid** [comment]
Hey @omaisali ,

fixed in https://github.com/realrashid/sweet-alert/commit/0dc2b0e9d7e7b2b3a5ba95511d52416f608cd2ae

**Comment by galayasa** [comment]
Problem 1
    - Root composer.json requires realrashid/sweet-alert 3.0 -> satisfiable by realrashid/sweet-alert[v3.0].
    - realrashid/sweet-alert v3.0 requires php ^7.2 -> your php version (8.1.3) does not satisfy that requirement.

**Comment by realrashid** [comment]
Hey @galayasa ,

Will soon add the support for updated PHP versions..😊

**Comment by realrashid** [comment]
Hey @galayasa ,

Will soon add the support for updated PHP versions..😊

**Comment by galayasa** [comment]
how to update php?

**Comment by galayasa** [comment]
Problem 1
    - Root composer.json requires realrashid/sweet-alert 3.0 -> satisfiable by realrashid/sweet-alert[v3.0].
    - realrashid/sweet-alert v3.0 requires php ^7.2 -> your php version (8.1.10) does not satisfy that requirement.
.
