### ISSUE TITLE
Can we change the positionof toste allert???? It kinda hides my nav bar. is there any option??

### ISSUE THREAD

**Issue by mangitmaharjan** [realrashid/sweet-alert#11]
## Detailed description

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. Laravel v5.6, SweetAlert2 v7.18.0):
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:

**Comment by realrashid** [comment]
Hello Dear,
```php
// toast('toast message','type','position');
toast('Your Toast Message Goes Here!','success','bottom-end');
```
position, can be 'top', 'top-start', 'top-end', 'center', 'center-start', 'center-end', 'bottom', 'bottom-start', or 'bottom-end'.
it's already mention in package readme before submitting issue please read the readme.

**Comment by mangitmaharjan** [comment]
i mean custom position
