### ISSUE TITLE
Animations are not being trigged

### ISSUE THREAD

**Issue by eaglefox82** [realrashid/sweet-alert#111]
I have installed this package via Composer into my Laravel Project. 
However I have not successfully trigged any animation of any alert.

I have followed all install steps as details, including publishing the package via cmd

The following provides a standard model
` if($currentstatus == "Y")
        {
            alert()->info('Member marked as attending', "Member has already been marked as attending")->autoclose(2000);
            return redirect(action('EventController@show', $r->event_id));
        }`

if I use the following
` if($currentstatus == "Y")
        {
           Alert::info('Member marked as attending', "Member has already been marked as attending")->autoclose(2000);
            return redirect(action('EventController@show', $r->event_id));
        }`
I get the same model popup

![image](https://user-images.githubusercontent.com/20160019/103496393-2baecd80-4e92-11eb-9ec7-1c5f12432d25.png)

I checked the confing/sweetalert.php
and found this
`'animation' => [
        'enable' => env('SWEET_ALERT_ANIMATION_ENABLE', false),
    ],`
So I set yo true and no difference.
I am using Laravel 7.13.0

Any help would be great

**Comment by realrashid** [comment]
Hey,

I have tested the package on fresh Laravel 8 installation with Laravel Sail it's working as expected.

![image](https://user-images.githubusercontent.com/15607685/103756952-e1645280-5031-11eb-87a5-f23c03f77bd3.png)

I use the same alert code as you mentioned.

![image](https://user-images.githubusercontent.com/15607685/103758116-8c294080-5033-11eb-9b47-af4df6613b6f.png)

You can see the working result as image.

![image](https://user-images.githubusercontent.com/15607685/103758352-e5916f80-5033-11eb-82f5-b49a7c8c7b7f.png)

You can also checkout the video too. 😄 

https://user-images.githubusercontent.com/15607685/103760339-c8aa6b80-5036-11eb-9ad6-ddb2b050da1a.mp4
