### ISSUE TITLE
Class 'RealRashid\SweetAlert\SweetAlertServiceProvider' not found

### ISSUE THREAD

**Issue by lavecart** [realrashid/sweet-alert#114]
In live server giving this error:
```
Class 'RealRashid\SweetAlert\SweetAlertServiceProvider' not found
```

I have added all of realrashid folder in vendor. Added 
```
RealRashid\SweetAlert\SweetAlertServiceProvider::class,
```
in ```app.php``` file. Also added `Alert` alias as the documentation guide me. 

Uploaded sweetalert.php in config folder. 

All are working in localhost but not in live cpanel server. What could be the problem?

**Comment by realrashid** [comment]
Hey @lavecart ,

First of all sorry for replying late.

Have you published package assets?

If not then run below command.

```sh
php artisan sweetalert:publish
```
If the issue still exist then the below commands too.

```sh 
php artisan cache:clear 
```

```sh 
php artisan config:clear 
```

Hope that will help. 👍

**Comment by haris365** [comment]
**Class 'RealRashid\SweetAlert\SweetAlertServiceProvider' not found**

i have added all the link in the particular file  , but same error 

i have also run the composer dumpautoload  as well but nothing happened , 

pelase help

**Comment by zibavar** [comment]
> In live server giving this error:
> 
> ```
> Class 'RealRashid\SweetAlert\SweetAlertServiceProvider' not found
> ```
> 
> I have added all of realrashid folder in vendor. Added
> 
> ```
> RealRashid\SweetAlert\SweetAlertServiceProvider::class,
> ```
> 
> in `app.php` file. Also added `Alert` alias as the documentation guide me.
> 
> Uploaded sweetalert.php in config folder.
> 
> All are working in localhost but not in live cpanel server. What could be the problem?

did is it solve ?

**Comment by realrashid** [comment]
Hey,

Can you share the error message?

**Comment by zibavar** [comment]
All are working in localhost but not in live cpanel server. What could be the problem?

**Comment by zibavar** [comment]
Class 'RealRashid\SweetAlert\SweetAlertServiceProvider' not found

**Comment by zibavar** [comment]
my server  is  linux and i dont have terminal in cpanel for ->php artisan sweetalert:publish

**Comment by realrashid** [comment]
Okay i search for a solution for you. Soon

**Comment by ivke013** [comment]
The some problem on live server!!!

**Comment by realrashid** [comment]
The update is on the way to you.

**Comment by vamshikrishnaakula** [comment]
Class "RealRashid\SweetAlert\SweetAlertServiceProvider" not found 

for me it working in local but not in test environment, 
when i checkout it to develop also it working fine in local,i have tried all even edited composer.json file also,can you please anyone help to clear this thankyou
