### ISSUE TITLE
Is it possible to running this package in Livewire component?

### ISSUE THREAD

**Issue by desyashasyi** [realrashid/sweet-alert#115]
I would like to know and maybe if there is available tutorial of using this package in Livewire Component. Thank you.

**Comment by realrashid** [comment]
Hey @desyashasyi ,

Yes, there you go https://dev.to/realrashid/how-to-use-sweetalert2-with-livewire-56i6 .

**Comment by desyashasyi** [comment]
Thank you very much brother,
how about using toast, is it same way with these tuotrial?
