### ISSUE TITLE
Documentation website not working

### ISSUE THREAD

**Issue by soumik9** [realrashid/sweet-alert#117]
Please check the website,

![Capture](https://user-images.githubusercontent.com/46122468/117545793-24b6e800-b049-11eb-95d0-41ad9522fb54.PNG)
[https://realrashid.github.io/sweet-alert/config](url)

**Comment by realrashid** [comment]
Hey 👋,

Website is working fine.

Just visit at https://realrashid.github.io/sweet-alert

Thanks & Regards.
