### ISSUE TITLE
Sweetalert major version released with a minor package tag

### ISSUE THREAD

**Issue by Okipa** [realrashid/sweet-alert#119]
- Package Version: 3.2.3
- Laravel Version: irrelevant

### Description:

Sweetalert has been released in v11 with some breaking changes.

This package is embedding this v11 with the 3.2.3 tag, which is wrong because Sweetalert has been upgraded to a new major version with a package minor tag  for all users.

In order to respect semantic versionning, it should have been released with a new 4.0.0 tag to prevent any desagrements.

It breaks apps for all users that are using Sweetalert with this package and with  small custom treatments.

Would it be possible to remove the 3.2.3 tag and to replace it with a 4.0.0 tag ?

### Steps To Reproduce:

`composer update`

**Comment by realrashid** [comment]
Hey @Okipa v4 for this package is coming on Friday.

❤️

**Comment by Okipa** [comment]
Hi @realrashid, perfect, thanks.

In the meantime, would it be possible to remove the 3.2.3 which is causing many breaking changes ?

We will upgrade to your v4 to use the v11 of Sweetalert 👍🏻
