### ISSUE TITLE
How can I override a method in Toaster class

### ISSUE THREAD

**Issue by o4itea** [realrashid/sweet-alert#121]
Hi,

I want to make a bit modification on "setDefaultConfig" and "middleware" methods in Toaster class.
How I can do that and where should I place my modification without touch the original files.

Sorry to post this here if it not related to issues.
Thanks

**Comment by o4itea** [comment]
Also I whould like to shere my modification, It may help someone.

In setDefaultConfig method I added 'showClass' & 'hideClass', So I can set a default animation.
In middleware method, It unset 'heightAuto', 'width', 'padding' without any way to reset, So I remove them.

**Comment by realrashid** [comment]
Hey @o4itea ,

It's very simple just like we override any parent class function in derived class.

You can try following :

Create a child class extending Toaster class and override the  "setDefaultConfig" and "middleware" methods.

```php

use RealRashid\SweetAlert;

Class ChildClass extends Toaster {

    public function setDefaultConfig () {
       // Write your logic here
    }

    public function middleware () {
       // Write your logic here
    }

}

```

Hope this will help.

**Comment by o4itea** [comment]
Thank Bro,
Where should I put the child class how to tell laravel to override parent class

**Comment by realrashid** [comment]
Create the Service Provider for overridden class. 
First parameter of bind function must be same as facade accessor of sweet-alert Facade [https://github.com/realrashid/sweet-alert/blob/master/src/Facades/Alert.php](check here). Register this facade in config/app.php after the service provider of sweet-alert package. :

```php

use RealRashid\SweetAlert;
use app\ChildClass;
Class ChildClassServiceProvider extends ServiceProvider {
    public function register(){
        $this->app->bind('alert', function(){
           return new ChildClass($this->app['config']);
        })
    }
}
```


Complete Code:

```php

// ChildClass

use RealRashid\SweetAlert;

Class ChildClass extends Toaster {

    public function setDefaultConfig () {
       // Write your logic here
    }

    public function middleware () {
       // Write your logic here
    }

}

```


```php

// ServiceProvider

use RealRashid\SweetAlert;
use app\ChildClass;
Class ChildClassServiceProvider extends ServiceProvider {
    public function register(){
        $this->app->bind('alert', function(){
           return new ChildClass($this->app['config']);
        })
    }
}
```

😊

**Comment by realrashid** [comment]
Create the Service Provider for overridden class. 

First parameter of bind function must be same as facade accessor of sweet-alert Facade [Check  here] (https://github.com/realrashid/sweet-alert/blob/master/src/Facades/Alert.php). Register this facade in config/app.php after the service provider of sweet-alert package. :


```php


use RealRashid\SweetAlert;

use app\ChildClass;

Class ChildClassServiceProvider extends ServiceProvider {
    public function register(){
        $this->app->bind('alert', function(){
           return new ChildClass($this->app['config']);
        })
    }
}

```



Complete Code:


```php


// ChildClass


use RealRashid\SweetAlert;

Class ChildClass extends Toaster {

    public function setDefaultConfig () {
       // Write your logic here
    }

    public function middleware () {
       // Write your logic here
    }

}


```



```php


// ServiceProvider


use RealRashid\SweetAlert;

use app\ChildClass;

Class ChildClassServiceProvider extends ServiceProvider {
    public function register(){
        $this->app->bind('alert', function(){
           return new ChildClass($this->app['config']);
        })
    }
}

```

**Comment by realrashid** [comment]
Create the Service Provider for overridden class. 
First parameter of bind function must be same as facade accessor of sweet-alert Facade [Check Here](https://github.com/realrashid/sweet-alert/blob/master/src/Facades/Alert.php). Register this facade in config/app.php after the service provider of sweet-alert package. :

```php

use RealRashid\SweetAlert;
use app\ChildClass;
Class ChildClassServiceProvider extends ServiceProvider {
    public function register(){
        $this->app->bind('alert', function(){
           return new ChildClass($this->app['config']);
        })
    }
}
```


Complete Code:

```php

// ChildClass

use RealRashid\SweetAlert;

Class ChildClass extends Toaster {

    public function setDefaultConfig () {
       // Write your logic here
    }

    public function middleware () {
       // Write your logic here
    }

}

```


```php

// ServiceProvider

use RealRashid\SweetAlert;
use app\ChildClass;
Class ChildClassServiceProvider extends ServiceProvider {
    public function register(){
        $this->app->bind('alert', function(){
           return new ChildClass($this->app['config']);
        })
    }
}
```

**Comment by o4itea** [comment]
Thanks Rashid, You've lighted the way in front of me.

The following code works
```php
// ServiceProvider

use App\ChildClass;
Class ChildClassServiceProvider extends ServiceProvider {
    public function register(){
        $this->app->bind('alert', ChildClass::class)
    }
}
```
or replace the facade with the targeted class
```php
// ServiceProvider

use RealRashid\SweetAlert\Toaster;
use App\ChildClass;
Class ChildClassServiceProvider extends ServiceProvider {
    public function register(){
        $this->app->bind(Toaster::class, ChildClass::class)
    }
}
```
