### ISSUE TITLE
show just one error when use the toast

### ISSUE THREAD

**Issue by ariaallahyari** [realrashid/sweet-alert#122]
- Package Version: 4.0.0
- Laravel Version: 8.5.0

### Description:
first ty for the awesome package 
when i use the toast for the form validation it just shows the last one error !
this is my code:
`@php`
` if (count($errors)>0){`
` foreach ($errors->all() as $error){`
`  toast($error,'error')->timerProgressBar();`
`}`
`}`
`@endphp`

i use the custom Request that return the array of messages.

**Comment by realrashid** [comment]
Hey ,

Yes the toast will show the first error 😊.
