### ISSUE TITLE
Can't be used in laravel 5.8 ?

### ISSUE THREAD

**Issue by SendyHartanto** [realrashid/sweet-alert#124]
- Package Version: v4.0
- Laravel Version: v5.8

### Description:
so i just try to install this sweetalert with this command "composer require realrashid/sweet-alert" , and then this message appear

![image](https://user-images.githubusercontent.com/33739034/138994303-23626209-b255-4ea2-b56d-675fbec6b31e.png)

actually, i always use this sweetalert for my project and it always work.. but i try to instal this package for my older laravel project.

### Steps To Reproduce:
1. install laravel 5.8
2. run command "composer require realrashid/sweet-alert"

**Comment by realrashid** [comment]
Fixed!
