### ISSUE TITLE
Add timerProgressBar to config

### ISSUE THREAD

**Issue by andreasmatu** [realrashid/sweet-alert#125]
Could you please add 'timerProgressBar' to config file?
I want to set this feature globally.

You could just add in Toaster.php into the setDefaultConfig() function (maybe i forgot something):
$this->config = [
...
'timerProgressBar' => config('sweetalert.timer_progress_bar'),
...];

I would appreciate this change!

**Comment by andreasmatu** [comment]
https://github.com/andreasmatu/sweet-alert/commit/4cffe1747876fb16c0107881bd62b93d46e608ae

**Comment by realrashid** [comment]
FIxed!
