### ISSUE TITLE
how to hide confirm button

### ISSUE THREAD

**Issue by amindeist** [realrashid/sweet-alert#127]
- Package Version: #.#.#
- Laravel Version: #.#.#

### Description:

i try to hide confirm button but it doesnt work form me!

alert()->success('Title','Message')->persistent(false,false)->autoClose(5000);

### Steps To Reproduce:

**Comment by realrashid** [comment]
Hey 👋,

You can turn it off from .env



SWEET_ALERT_CONFIRM_BUTTON=false

**Comment by realrashid** [comment]
Closed due to inactivity.
