### ISSUE TITLE
how can i call alert with ajax

### ISSUE THREAD

**Issue by amindeist** [realrashid/sweet-alert#128]
- Package Version: #.#.#
- Laravel Version: #.#.#

### Description:
``
hi
i need to call alert with ajax like this below but it doesnt work

`$.ajax({
           url:"{{ route('contact.store') }}",
           data: formData,
           type: 'POST',
           dataType: 'JSON',
           processData: false,
           contentType: false,
           success: function (data){
               if(data.success){
                   Swal.fire({
                       icon: 'success',
                       title: 'Thanks',
                       text: "thank you for contacting us"
                   });
               }else{
                   Swal.fire({
                       icon: 'error',
                       title: 'Oops...',
                       text: "please fill data!"
                   });
               }
           }
       });`

### Steps To Reproduce:

**Comment by realrashid** [comment]
Hey @amindeist ,

This package does not support to call the ajax using PHP but you can call the ajax on your script.
