### ISSUE TITLE
Toast without closing button, for the EU Cookie Law

### ISSUE THREAD

**Issue by StanBarrows** [realrashid/sweet-alert#13]
Hey there, 

first of all thanks for your package! To apply the EU Cookie Law, I would like to implement a Toast without a closing button but with a confirmation button.

I tried to implement it with your documentation but I'm failing. 

**Current Code:**
```
toast('We love cookies, whats about you?','question','bottom-right')->showConfirmButton('Accept','#3085d6');

```
**Result:**
<img width="508" alt="cookies" src="https://user-images.githubusercontent.com/10268813/41492163-8787949a-70fd-11e8-9e1e-eeaa94ee325c.png">

I tried to add:
```
->persistent(false,true);
```

Is there a chance to achieve it somehow? Something wihtout the X inside the red square.
<img width="527" alt="closing" src="https://user-images.githubusercontent.com/10268813/41492260-3fff8366-70fe-11e8-8d93-3b1785340e09.png">

Cheers, 
Stan Barrows

**Comment by StanBarrows** [comment]
I found out that you could basically disabel it inside the vendor folder, but it would be nice if we could somehow pass it by a parameter.

```
public function toast($title, $type, $position = 'top-right')
    {
        $this->config['toast'] = true;
        $this->config['title'] = $title;
        $this->config['showCloseButton'] = false
        $this->config['type'] = $type;
        $this->config['position'] = $position;

        $this->flash();

        return $this;
    }```


Cheers, 
Stan

**Comment by realrashid** [comment]
Hi @StanBarrows ,

First of all thank for using the package!

Yes you can achieve this without making any changes to vendor files.

``` php
alert()->question('We love cookies, whats about you?', '')->toToast('bottom-right')->showConfirmButton('Accept', '#3085d6')->persistent(false, true);
``` 
![screenshot_2018-06-17 laravel](https://user-images.githubusercontent.com/15607685/41506749-277948dc-723d-11e8-8805-8e3e9ffc263c.png)

Hope that solve your issue!

**Comment by StanBarrows** [comment]
Hi @realrashid, thanks for your help.

The is a small typo in your example.

`->persistent(false, false);`

Do you know how I can set a href="{{ route('') to a button?

Cheer, 
Stan

**Comment by realrashid** [comment]
It's not implemented in this version but thanks for knowing me will add this in new version.
