### ISSUE TITLE
 Alert::image function modification

### ISSUE THREAD

**Issue by saeed410** [realrashid/sweet-alert#134]
- Package Version: 5.0

### Description:
Alert function with image last argument must be nullable and Documentation needs to be modified.
Alert::image() accept 6 argument and last argument is optinal. but in RealRashid\SweetAlert\Toaster class the six argument not considered as null. It produces an error if we proceed according to the documentation. This function should be modified as follows:  
`
 public function image($title, $text,$imageUrl, $imageWidth, $imageHeight, $imageAlt= null)
    {
...
}
`

**Comment by realrashid** [comment]
Hey ☺️

This will be fix very soon.

Thanks 😊
