### ISSUE TITLE
handle different config above default .env

### ISSUE THREAD

**Issue by GergoKormoczy** [realrashid/sweet-alert#135]
I already added this SWEET_ALERT_CONFIRM_BUTTON=false (well documented & working fine) this is default but has some modal when i need confirm button || cancelButton maybe, how can i handle this situation?

**Comment by realrashid** [comment]
Hey @GergoKormoczy ,
You can use the helper method.

```php 
// example:
alert()->success('SuccessAlert','Lorem ipsum dolor sit amet.')->showConfirmButton('Confirm', '#3085d6'); ``` 

```php

// example:
alert()->question('Are you sure?','You won\'t be able to revert this!')->showCancelButton('Cancel', '#aaa');

```

Hope that's helped ☺️.

**Comment by realrashid** [comment]
Closed due to inactivity
