### ISSUE TITLE
Alert::warning oversized

### ISSUE THREAD

**Issue by thegenzo** [realrashid/sweet-alert#137]
- Package Version: 5.0.0
- Laravel Version: 8.83.6

Hi, when I am generating Alert::warning notification from my Laravel app, it just don't look good because the alert size is too big I think, compared to Alert::success or Alert::error size. 
![image](https://user-images.githubusercontent.com/23573634/165889430-b5fa9725-0aac-405e-8b41-14df34985126.png)

How to fix that? 
Thank you

**Comment by realrashid** [comment]
Hey @thegenzo ,

Does the other type of alerts are in their normal sizes??

Try the width helper method.


```php

// example: alert('Title','Lorem Lorem Lorem', 'success')->width('720px');

```

Let me know if that works and please also checkout your css libraries sometimes they conflict with package library.

**Comment by thegenzo** [comment]
Hi @realrashid ,
Yes, the other type is in their normal sizes.

> // example: alert('Title','Lorem Lorem Lorem', 'success')->width('720px');

It didn't come to normal size, but I think the looks is slightly better
![image](https://user-images.githubusercontent.com/23573634/166075020-d99ccf80-1b2f-404e-9e58-9971a23fdab0.png)

**Comment by thegenzo** [comment]
[SOLVED]

So I tried to use sweetalert2 asset via CDN on:
` https://www.jsdelivr.com/package/npm/sweetalert2 `
and turns out the size of Alert::warning is normal. I guess it's only matter of sweetalert2 asset version.
