### ISSUE TITLE
Uncaught ReferenceError: swal is not defined detele function not working

### ISSUE THREAD

**Issue by vinithav** [realrashid/sweet-alert#138]
## My code
 $(function() {
    $(document).on('click', '.text-danger', function() {

      var id = $(this).attr('id');
      var $ele = $(this).parent().parent();
      var rate_delete = 'rate_delete';

      swal({
          title: "Are you sure?",
          text: "Do You Really Want to Delete !",
          icon: "warning",
          buttons: true,
          dangerMode: true,
        })
        .then((willDelete) => {
          if (willDelete) {
            $.ajax({
              type: 'POST',
              url: 'ajax-helper.php',
              data: {
                'id': id,
                rate_delete: rate_delete
              },
              success: function(data) {
                $ele.fadeOut().remove();
                location.reload();
              }
            });
          } else {}
        });
    });
  });

**Comment by realrashid** [comment]
Hey @vinithav ,

Use 

```javascript

Swal.fire({});

```

And also enabled the alwaysLoadJS in you .env file 

`SWEET_ALERT_ALWAYS_LOAD_JS=true`

**Comment by realrashid** [comment]
Closed due to inactivity
