### ISSUE TITLE
VS Code - intelephense(1009) error

### ISSUE THREAD

**Issue by iwansw** [realrashid/sweet-alert#140]
- Sweet-Alert Package Version: v5.1.0
- Laravel Version: v9.19.0 
- VS Code Version v1.70.0

### Description:
Hi, I'm happy to use this alert and works well in my application.
But it's bit annoying to see VS Code gives "intelephense(1009) error" for the **Alert** class as shown;

![image](https://user-images.githubusercontent.com/50900696/184063514-b874f6e0-506c-4ca3-8e77-d053e7d8f120.png)

I'm still new in Laravel, hope there's a way to fix this ... since we like to see our code clean & sharp, thank you.

**Comment by realrashid** [comment]
Hi 👋,



Intelephense 1.3 added undefined type, function, constant, class constant,
method, and property diagnostics, where previously in 1.2 there was only
undefined variable diagnostics.

The package has some variables that not be defined by default that's why vs
code throw intelephense error.

**Comment by realrashid** [comment]
Closed Due to inactivity..

**Comment by iwansw** [comment]
Hi,

Turns out it just need to restart VS Code, after installing SWAL & publish to config .. for some reason pHp Intelephense does not initialize SWAL automatically. Restarting VS Code fix the issue ... Thank You
