### ISSUE TITLE
Not working with Laravel Livewire :(

### ISSUE THREAD

**Issue by rosolovsky** [realrashid/sweet-alert#142]
Not working with Laravel Livewire :(

**Comment by realrashid** [comment]
Please share the installation steps..

**Comment by rosolovsky** [comment]
Installation done according to documentation. Package is working in pure Laravel, but not in Livewire components.

**Comment by realrashid** [comment]
Hey @rosolovsky ,

I have tested the package with Livewire it's working as excepted as you can see the image below.

 
![livewire](https://user-images.githubusercontent.com/15607685/189878026-2778c15d-b988-44b4-8b94-993659144cec.png)


Please share the error here maybe I will help you.

**Comment by rosolovsky** [comment]
@include('sweetalert::alert') 
This directive not load SweetAlert js library in my case. In addition, the sweetAlert2-function "Swal.fire" is not present in the sorce code of the page. This is the reason.

**Comment by Sisableng** [comment]
> @include('sweetalert::alert')

i have same issue, and i trying to add `@include('sweetalert::alert')` in livewire blade views, its work fine even you set `redirect()->back()`

just add `@include('sweetalert::alert')` in your livewire views
