### ISSUE TITLE
Select Box contain automatically

### ISSUE THREAD

**Issue by Piccolo27** [realrashid/sweet-alert#144]
- Package Version: latest
- Laravel Version: 9

### Description:
When I use` Alert::success("Hello"),`
the select box I don't want is showing along with the alert. How can I remove this select box?

### Steps To Reproduce:
![Screenshot from 2022-11-09 22-13-33](https://user-images.githubusercontent.com/106439979/200875211-255534e8-8095-4151-a45a-399b5c4002e2.png)

**Comment by realrashid** [comment]
Dear @Piccolo27 ,

Please inspect your other JS libraries that conflicting the package..

I recommend you to comment out the others libraries one by one in this way you will find out which library is creating the select box.

If you found then just put the sweetalert js to the top of that library.
