### ISSUE TITLE
Uncaught ReferenceError: Swal is not defined

### ISSUE THREAD

**Issue by ahmedelbaiomy** [realrashid/sweet-alert#146]
- Package Version: #.#.#
- Laravel Version: #.#.#

### Description:
i run composer command to install package then , i include  sweet alert in (app.blade.php)
the sweetalert not working with me 

![image](https://user-images.githubusercontent.com/77383056/212800964-08780f2f-72bc-4b2f-805f-7f23f8cc69cb.png)

### Steps To Reproduce:

**Comment by realrashid** [comment]
Please share the complete steps have you done with screenshot.

That will help me to find out the actual cause of error.

**Comment by ClassicSignum** [comment]
![image](https://user-images.githubusercontent.com/47184720/220559078-9cf1d397-4ba3-437c-88c3-cbd5b6679f9f.png)

changes should be made here in views/vendor/sweetalert/alert.blade.php 
Mine works fine after doing this
