### ISSUE TITLE
Multiple alerts

### ISSUE THREAD

**Issue by StanBarrows** [realrashid/sweet-alert#15]
Hello everybody,

Is there a way to show multiple alerts? Or at least the latest alert that's getting fired?

Scenario:

There's a cookie law that I have to implement with an alert (bottom-right). Now I still would like to show other toasts or alerts that are displayed somewhere else on the screen (middle).

![alerts](https://user-images.githubusercontent.com/10268813/43022112-6974abc6-8c66-11e8-8c15-df1368e71fb4.jpg)

Thanks for any feedback,
Stan

**Comment by realrashid** [comment]
Hi @StanBarrows ,

I was think a while i came up with no i can't show multiple alerts i set this is a bug and will fix it near feature version.

Thanks.

**Comment by belzaaron** [comment]
@realrashid, if you will be fixing it why close it then? Just wondering your about your work flow? Never seen a process like this..

**Comment by realrashid** [comment]
@belzaaron Thank you !

**Comment by realrashid** [comment]
Hello @StanBarrows  please read this sweetalert2/sweetalert2#808
