### ISSUE TITLE
Unable to add background config on sweetalert config

### ISSUE THREAD

**Issue by rmiqbalramadhan** [realrashid/sweet-alert#154]
- Package Version: 9.0.#
- Laravel Version: 6.0.#

### Description:
I'm trying to add `'background' => env('SWEET_ALERT_BACKGROUND', '#242d28')` in sweetalert.php but this config is not applied. Your helper `->background()` works fine, but what I'm trying to accomplish is can I put it in sweetalert config? Maybe I'm missing something?. Thanks in advance.

### Steps To Reproduce:
1. Go to config sweetalert.php
2. add 'background' => env('SWEET_ALERT_BACKGROUND', '#242d28')
3. try toast/alert trigger
4. no background change

**Comment by realrashid** [comment]
Will be fix in coming version very soon.
