### ISSUE TITLE
How to use alert in livewire component?

### ISSUE THREAD

**Issue by dubbows** [realrashid/sweet-alert#156]

**Comment by umefarooq** [comment]
Hi use this livewire component work nice https://github.com/jantinnerezo/livewire-alert

**Comment by dubbows** [comment]
config/sweetalert.php
![Captura de Tela 2023-05-23 às 11 02 08](https://github.com/realrashid/sweet-alert/assets/34485877/1e75c455-3d7d-4517-9460-fb6ab1b564e2)

**Comment by dubbows** [comment]
in livewire component
![Captura de Tela 2023-05-23 às 11 03 21](https://github.com/realrashid/sweet-alert/assets/34485877/9f3344bd-7473-4443-9f40-d803c29cd78b)

**Comment by dubbows** [comment]
in method use facade alert its works
![Captura de Tela 2023-05-23 às 11 04 33](https://github.com/realrashid/sweet-alert/assets/34485877/3430110d-a463-48dd-825f-204d10cfa1b8)
