### ISSUE TITLE
confirmDelete feature has unexpected behavior

### ISSUE THREAD

**Issue by mohamedds-12** [realrashid/sweet-alert#157]
- Package Version: 7.0.0
- Laravel Version: 8

### Description:
When using the feature of confirmDelete(): 
- It only works on the first delete button and doesn't work on others.
- Sometimes it works on the second button not on the first.
- After the popup shows and hitting cancel and then hitting the button, it just deletes the item without the popup being showed.

### Steps To Reproduce:
Like described in the Docs.

**Comment by realrashid** [comment]
Hey,

Can you share the codes or something that's me to figure it out 🤔

**Comment by mohamedds-12** [comment]
After some testing, turns out when I do a button without the text just the trash icon then it acts weirdly : 
```html
<a href="{{ route('roles.destroy', $role) }}" class="btn btn-danger" data-confirm-delete="true"><i class="fa-solid fa-trash"></i></a>
```

**Comment by realrashid** [comment]
Hey checkout how i did.

View
```php
@foreach ($users as $user)
    <tr>
        <td>{{ $user->id }}</td>
        <td>{{ $user->name }}</td>
        <td>{{ $user->email }}</td>
        <td>
            <a href="{{ route('users.edit', $user->id) }}" class="btn btn-primary">Edit</a>
            <a href="{{ route('users.destroy', $user->id) }}" class="btn btn-danger" data-confirm-delete="true">Delete</a>
        </td>
    </tr>
@endforeach
```

Routes
```php
Route::delete('/users/{user}', [App\Http\Controllers\UsersController::class, 'destroy'])->name('users.destroy');
Route::get('/users/{user}', [App\Http\Controllers\UsersController::class, 'delete'])->name('users.delete');
```
Controller Index Method
```php
public function index()
    {
        $users = User::latest()->paginate(10);

        $title = 'Delete User!';
        $text = "Are you sure you want to delete?";
        confirmDelete($title, $text);
        return view('users.index', compact('users'));
    }
```

Controller Destroy Method

```php
public function destroy(User $user)
    {

        $user->delete();

        return redirect()->route('users.index')->withSuccess('User deleted successfully.');
        alert()->success('User deleted successfully.');
    }
```

Hope That's helped.

**Comment by mohamedds-12** [comment]
Your code would work fine, but if you remove the "Delete" or "Edit" text then it would not work.
Try to change your html into this and see : 
```php
@foreach ($users as $user)
    <tr>
        <td>{{ $user->id }}</td>
        <td>{{ $user->name }}</td>
        <td>{{ $user->email }}</td>
        <td>
                <a href="{{ route('users.destroy', $user->id) }}" class="btn btn-danger" data-confirm-delete="true">
                        <i class="fa-regular fa-trash"></i>
            </a>
        </td>
    </tr>
@endforeach
```

**Comment by mohamedds-12** [comment]
@realrashid hey there, anything on this issue

**Comment by realrashid** [comment]
Hey sorry for not responding because i am busy with some projects and a new
package for Laravel.

I will fix this issue as soon as possible.

Then you will be able to use it with any tag.

Thanks for using it by the way.

**Comment by mohamedds-12** [comment]
Thanks to you for developing such a helpful package. ok can't wait to see it fixed.

**Comment by isousluer** [comment]
I think I solved the problem. I'm also using svg icon inside the a tag, that's why it wasn't clicking. I gave the value data-confirm-delete="true" to all elements inside the a tag. I also gave it to the a tag. Then I changed line 21 of the alert.blade.php file as follows. I am using it without any problems now. I hope I was able to help.

`<a href="{{ route('warehouse.destroy', $warehouse) }}" class="btn btn-danger btn-sm" data-confirm-delete="true">
                                                    <svg data-confirm-delete="true" fill="#fff" xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 24 24">
                                                        <path data-confirm-delete="true" d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5l-1-1h-5l-1 1H5v2h14V4z" />
                                                        <path data-confirm-delete="true" fill="none" d="M0 0h24v24H0V0z" />
                                                    </svg>
                                                </a>`

alert.blade.php:

`form.action = event.target.closest('a').href;`

**Comment by rioovs** [comment]
i got same problem, when i click for first time sweet alert is perfeckly worked and when i press cancel and press delete again. the problem showing

**Comment by paulorlima9** [comment]
Hello, I'm facing the same problem.

**Comment by ihsanpraditya** [comment]
Hello, I'm facing it too. When I set the config in `.env` the popup is not showing at all.
