### ISSUE TITLE
my sweet alert not displaying 

### ISSUE THREAD

**Issue by Lakeguru** [realrashid/sweet-alert#16]
## Detailed description

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. Laravel v5.6, SweetAlert2 v7.18.0):
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:

**Comment by belzaaron** [comment]
We need you to fill out the details, like:
- Detailed description
- Context
- Environment

Please edit your issue and provide these details.

**Comment by realrashid** [comment]
Hello @Lakeguru ,

Please share the error message or screenshot.

I'm closing the issue at the moment when you have error message or screenshot you can re-open the same issue.

Thanks
