### ISSUE TITLE
Separate btw "confirmDelete"'s confirm button and the "alert"'s confirm button

### ISSUE THREAD

**Issue by mohamedds-12** [realrashid/sweet-alert#161]
In the package config there's only one config key `SWEET_ALERT_CONFIRM_BUTTON=true` that determines whether to show the confirm button on alerts or not. But after adding the `confirmDelete` feature the confirm button of the "confirmDelete" alert must be shown although I don't want it to be shown on normal alerts. and that's not possible cuz only one key determines whether it must be shown in all alerts or not.

**Comment by realrashid** [comment]
Hey @mohamedds-12 ,

In the new release when you use `confirmDelete()` its automatically show the confirm button rather you have  `SWEET_ALERT_CONFIRM_BUTTON=false` or `SWEET_ALERT_CONFIRM_BUTTON=true`

**Comment by mohamedds-12** [comment]
@realrashid,
Well that's what I expected, but when I set the env key `SWEET_ALERT_CONFIRM_BUTTON` to false the confirm button "Yes, delete it" disappears.
Package version : 
![image](https://github.com/realrashid/sweet-alert/assets/92916932/d06b78c3-9901-42ab-b908-d69c16973a72)
