### ISSUE TITLE
confirmDelete issue

### ISSUE THREAD

**Issue by esglobal** [realrashid/sweet-alert#162]
- Package Version: 7.0.0
- Laravel Version: 10.15.0

### Steps To Reproduce: Just replace 

`<a href="{{ route('users.destroy', $user->id) }}" class="btn btn-danger" data-confirm-delete="true">Delete</a> `

with 

`<a href="{{ route('users.destroy', $user->id) }}" class="btn btn-danger" data-confirm-delete="true"><i class="fa fa-fw fa-times"></i></a>`

**Comment by esglobal** [comment]
Update: it works if you use the icon AND a text but doesn't work if we use just an icon the the a tag.

**Comment by thobiasvicente** [comment]
It appears that there is a bug when there's an icon, and upon clicking it, the click action is triggered on the icon itself rather than on the <a> tag. This doesn't make any sense, but I tried a workaround, and it worked. I did this:

```
<a href="{{ $action }}"
   class="h-10 w-10 bg-red-500 text-white flex items-center justify-center rounded-full"
   data-confirm-delete="true">
	<i data-confirm-delete="true" class=" fa fa-fw fa-trash"></i>
</a>
```
Just add `data-confirm-delete="true"` on the icon

**Comment by esglobal** [comment]
It works fine. Thanks @thobiasvicente
