### ISSUE TITLE
Ação do botão de confirmação

### ISSUE THREAD

**Issue by cassiobartolo** [realrashid/sweet-alert#163]
- Package Version: 7.0.0
- Laravel Version: 10.13.2

Não consigo colocar link no show_confirm_button, teria como fazer isso e como seria??

**Comment by realrashid** [comment]
Hey @cassiobartolo ,

I didn't get can say in English?

**Comment by cassiobartolo** [comment]
I already figured out how to do it, thanks for your attention.
