### ISSUE TITLE
Toast auto close not working

### ISSUE THREAD

**Issue by mohamedds-12** [realrashid/sweet-alert#164]
Using the middleware, 
![image](https://github.com/realrashid/sweet-alert/assets/92916932/32f0cb61-e9fc-475c-9a10-9d18a6a74b01)
alert close time works for the modals only but not for the toast. the toast stays displayed.
#87

**Comment by realrashid** [comment]
You should use `SWEET_ALERT_MIDDLEWARE_AUTO_CLOSE=true` by default its false.
