### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by BrickZ28** [realrashid/sweet-alert#166]
- Package Version: Latest
- Laravel Version: Latest

I'm encountering difficulty activating Dark Mode despite configuring it as the default in both the settings and the environment file. Despite these adjustments, my alerts persist in displaying in light mode. Could there be another location where Dark Mode must be enabled? It seems that, regardless of the theme setting I choose, the colors remain consistently light.

**Comment by realrashid** [comment]
Hey @BrickZ28 ,

Can you try to run 

```bash

php artisan optimize:clear
```

Maybe you are facing a cache issue.

To enable the dark mode theme there's just one thing to do.

```php

SWEET_ALERT_THEME="dark"
```

**Comment by BrickZ28** [comment]
I have tried that as well as clearing all cache for virws and routes

**Comment by realrashid** [comment]
When you set the theme to dark please set the `SWEET_ALERT_BACKGROUND` to empty in the `.env`

Such as `SWEET_ALERT_BACKGROUND=""` 

![image](https://github.com/realrashid/sweet-alert/assets/15607685/37becbb6-e345-43ba-99e9-58bd86d5143f)
