### ISSUE TITLE
Alert doesnot appears, Please help

### ISSUE THREAD

**Issue by theenescresta** [realrashid/sweet-alert#19]
Hello, I want to use this sweet-alert and i have included it in composer 
   "realrashid/sweet-alert": "^1.1",

and in controller i have used 
use RealRashid\SweetAlert\Facades\Alert;
 
![image](https://user-images.githubusercontent.com/33285099/45616526-7329a980-ba8f-11e8-9d90-927ed6a76a80.png)

in backend i have linked script as 
![image](https://user-images.githubusercontent.com/33285099/45616563-8dfc1e00-ba8f-11e8-82bd-63b193dcbeda.png)

in view file 
![image](https://user-images.githubusercontent.com/33285099/45616599-abc98300-ba8f-11e8-819c-d406e07877d5.png)
![image](https://user-images.githubusercontent.com/33285099/45616776-27c3cb00-ba90-11e8-9c3e-681be216f712.png)

then also I cant get any alert and there are no errors please help.

* Version used (e.g. Laravel v5.5, SweetAlert2 v7.18.0):

**Comment by theenescresta** [comment]
There is an error in console 
Uncaught ReferenceError: swal is not defined at create:623

**Comment by realrashid** [comment]
Ok i got it

did you follow my suggestion or did fixed your issue?

```php 
<script src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js"></script>
@include('sweetalert::alert')
```

**Comment by theenescresta** [comment]
yes i have done that but at last of the backend page 
![image](https://user-images.githubusercontent.com/33285099/45686014-f4a23a00-bb6a-11e8-99e7-04948fcbe3fe.png)
and the error is still appearing in console
![image](https://user-images.githubusercontent.com/33285099/45686236-9a55a900-bb6b-11e8-8115-1dc87e29ceed.png)

**Comment by theenescresta** [comment]
???

**Comment by ladaposamuel** [comment]
use the helpers instead , i had similar issues.
e.g instead of 
`Alert::info('','')`
use
`alert()->info('InfoAlert','Lorem ipsum dolor sit amet.')`

**Comment by realrashid** [comment]
The issue is with sweetalert2 js library you should download the library and use it from your assets.

Hope that will solve the issue that you are facing..

and the good news is i will load the sweetalert2 js library out of the box so you don't need to load it's cdn.

**Comment by realrashid** [comment]
The issue is with sweetalert2 js library you should download the library and use it from your assets.

Hope that will solve the issue that you are facing..

and the good news is i will load the sweetalert2 js library out of the box in upcoming version so you don't need to load it's cdn.

**Comment by FlorinGgc** [comment]
need help , There is an error in console
Object of type RealRashid\SweetAlert\Facades\Alert is not callable .... please
