### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by ilkonbilisim** [realrashid/sweet-alert#2]
My Form
<pre>{{Form::open(['url'=>'admin/settings/api', 'class'=>'form-horizontal','method' =>'post',  'files' => true])}}
                        {{Form::token()}}
                        {{Form::bsText('f_app_id','Facebook App Id',$settings->f_app_id)}}
                        {{Form::bsText('f_app_secret','Facebook App Secret',$settings->f_app_secret)}}
                        {{Form::bsText('f_page_id','Facebook Page Id',$settings->f_page_id)}}
                        {{Form::bsText('f_page_token','Facebook Page Token',$settings->f_page_token)}}
                        {{Form::submit('Save',['class' => 'btn btn-success m-r-10'])}}
                        {{Form::close()}}
			@if (alert()->ready())
			<script>
			swal({
			title: "{!! alert()->message() !!}",
			text: "{!! alert()->option('text') !!}",
			type: "{!! alert()->type() !!}"
			});
			</script>
			@endif
</pre>
My Controller
<pre>
public function api_update(Request $request){
        try{
            unset($request['_token']);
            Settings::where('id',1)->update($request->all());
            return alert()->flash('Ok!', 'success', [
                'text' => 'You have successfully completed your transaction.'
            ]);
        }
        catch (\Exception $e) {
            return alert()->flash('No!', 'error', [
                'text' => 'System failure! Please try again later.'
            ]);
        }
    }
</pre>

the message is not returning

How can I do it with ajax at once

I learn new to laravel please help me

**Comment by realrashid** [comment]
Hi,
its because you are not returning any view alert can not return from controller its render from views so you have to use views.
