### ISSUE TITLE
Package Auto Discovery is not working properly

### ISSUE THREAD

**Issue by aaranta** [realrashid/sweet-alert#22]
After composer package installation in Laravel 5.7, the usage of "Use Alert;" in the controller is not successful. We have to use "use RealRashid\SweetAlert\Facades\Alert;" instead.

Root cause is the package auto discovery was not handled properly.
bootstrap\cache\packages.php

 array (
   ||
    'aliases' => 
    array (
      'Alert' => 'RealRashid\\SweetAlert\\Facades',  <--missing "\\\Alert" at the back.
    ),

**Comment by realrashid** [comment]
#23
