### ISSUE TITLE
Laravel v5.7 not support?

### ISSUE THREAD

**Issue by eric2100** [realrashid/sweet-alert#23]
Laravel v5.7
Operating system Windows 10

in Controller

Use Alert;
    function test()
    {
        alert()->success('Post Created', 'Successfully');
    }

Chrome browser does not show anything.

**Comment by realrashid** [comment]
This will be solve in new version and its on way.

**Comment by Hassan247** [comment]
> This will be solve in new version and its on way.

When will that be?

**Comment by MuhammadAbran** [comment]
not work in 5.7

**Comment by realrashid** [comment]
Bug Fix in https://github.com/realrashid/sweet-alert/releases/tag/v1.1.1

**Comment by eric2100** [comment]
thank you.

**Comment by realrashid** [comment]
your welcome @eric2100 

happy coding!
