### ISSUE TITLE
alert()->html();

### ISSUE THREAD

**Issue by abgrano** [realrashid/sweet-alert#24]
your version 1.1.1
alert()->html(); Did not appear the icon. Others working fine.

**Comment by realrashid** [comment]
```php
alert()
->html("You can use <b>bold text</b>, 
		<a href='//github.com'>links</a> and other HTML tags",'info','<strong>HTML <u>example</u></strong>')
	->showConfirmButton('<i class="fa fa-thumbs-up"></i> Great!')
	->showCloseButton();
```

```php
// params
alert()->html($code = '', $type = '', $title = '');
```
```php
// params
showConfirmButton($btnText = 'Ok', $btnColor = '#3085d6');
```

```php
// params
showCancelButton($btnText = 'Cancel', $btnColor = '#aaa')
```

in the attached image you see the icon for the icon you must include font-awesome.

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
```

![example](https://user-images.githubusercontent.com/15607685/48223223-643ce480-e3b8-11e8-851c-c845daf64311.PNG)

Hope this helped.
Please let me know.

**Comment by abgrano** [comment]
Your previous version is **alert()->html($title = '', $code = '', $type = '');**
Now you change like this in version 1.1.1 is **alert()->html($code = '', $type = '', $title = '');**

Now i can fix the problem.

**THANKS.**

**Comment by abgrano** [comment]
GOOD WORK.

**Comment by abgrano** [comment]
In my opinion, the previous one is easy to assign. Like this alert()->html($title = '', $code = '', $type = '');
