### ISSUE TITLE
Get current user issue.

### ISSUE THREAD

**Issue by malfianrasyidin** [realrashid/sweet-alert#25]
Hi,

I use `Auth::user()` on every of my blade templates to show current logged in user. But, in console it show error 500 on getting `Auth::user()` on this package.

> http://localhost:8000/vendor/sweetalert/sweetalert.all.js

This route always return null on `Auth::user()`. How can I resolve this problem?

Fyi, I use Laravel 5.5 and sweet-alert ^1.1.

Thank you for your help!

**Comment by realrashid** [comment]
Did you run
 ```bash 
php artisan vendor:publish --tag=public 
```
above command?

**Comment by shadowsberg** [comment]
This work for me, thks

**Comment by malfianrasyidin** [comment]
That works, thank you!
