### ISSUE TITLE
helper() Documentation

### ISSUE THREAD

**Issue by abgrano** [realrashid/sweet-alert#26]
### Description:
Your documentation :  alert()->html('<i>HTML</i> <u>example</u>'," You can use <b>bold text</b>, <a href='//github.com'>links</a> and other HTML tags ",'success');

alert()->html('title', 'code', 'type');

### Steps To Reproduce:
Should be alert()->html('code', 'type', 'title');

**Comment by realrashid** [comment]
Yes dear i have seen when you create #24 issue.
This will be update soon.
