### ISSUE TITLE
Uncaught ReferenceError: swal is not defined

### ISSUE THREAD

**Issue by hoekie** [realrashid/sweet-alert#3]
Hi, Rashid

I had to wrap the alert in a section: (in this case 'scripts')

```
@section('scripts')
    @if (alert()->ready())
        <script>
            swal({
                title: "{!! alert()->message() !!}"
            });
        </script>
    @endif
@endsection
```

And then add:

`@yield('scripts')`

below my other script files in the layout template to make it work.
Otherwise a get an Uncaught ReferenceError: swal is not defined error.

Can you tell me why or is there another workaround to do this?

Thank you for this package!

Richard

**Specifications:**

- PHP Version: 7.1.9
- Laravel Version: 5.6

**Comment by realrashid** [comment]
Hi, 

You just add the CDN links in the head section like below

``` html
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.9/sweetalert2.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.9/sweetalert2.min.js"></script>
</head>
```
add the yield after the content yield like below

``` php
@yield('content')
{{-- Here --}}
@yield('scripts')
```
now you can use this with any view that extended the layout 

``` php
@section('scripts')
    @if (alert()->ready())
        <script>
            swal({
                title: "{!! alert()->message() !!}",
                type: "{!! alert()->type() !!}",
                @if (alert()->option('timer'))
                    timer: {!! alert()->option('timer') !!},
                    showConfirmButton: false
                @endif
            });
        </script>
    @endif
@endsection
```
**note: in my case the layout file is layout/app.blade.php**

#### **Thank you for using the package!**

**Comment by hoekie** [comment]
Thanks @realrashid !

That's exactly what I did.

Maby you should add this to your documentation in order to help newbees like me... ;)

**Comment by realrashid** [comment]
Yes sure! maybe in v1.1 will releasing soon.
I changed the entire workflow and i make it easy as i can.

**Comment by hoekie** [comment]
Cool! I'll keep an eye on this repository!

Thanks @realrashid

**Comment by hoekie** [comment]
Good job @realrashid !

Thanks!

**Comment by realrashid** [comment]
Your welcome @hoekie !

Thanks again!

**Comment by praveenkalaiarasu** [comment]
The solutions works for all sweetalert message types. Thanks.

But, I am finding hard to use toast messages using this type.
Can you please help ?

**Comment by realrashid** [comment]
Hi @praveenkalaiarasu ,
This issue came in version 1.0 and toast was not added in version 1.0 toast added in version 1.1.

**Comment by Arafatul-Rahman** [comment]
my code not work

**Comment by realrashid** [comment]
Hey @Arafatul-Rahman ,

Can you share the actual error here?

This will help me to understand your issue.

**Comment by realrashid** [comment]
Hey @Arafatul-Rahman ,

Can you share the actual error here?

This will help me to understand your issue.

**Comment by MFaizy-crypto** [comment]
Hello sir i need help 

(index):93 Uncaught ReferenceError: Swal is not defined
    at (index):93
(anonymous) @ (index):93

this type of error can i solve it ?

**Comment by realrashid** [comment]
Hey 👋

Did you published the package assets?

If not then run the below command.

```sh
php artisan sweetalert:publish
```

**Comment by realrashid** [comment]
Hey 👋

Did you included the 'sweetalert::alert' in master layout?

**Comment by ashique357** [comment]
Call to undefined method RealRashid\SweetAlert\Toaster::ready()

**Comment by qasim070** [comment]
Compiled with problems:
ERROR
[eslint] 
src\components\TextForm.js
  Line 48:9:  'Swal' is not defined  no-undef

Search for the keywords to learn more about each error.

facing this React.js
