### ISSUE TITLE
Upgrade SweetAlert2 to latest version, 8.x

### ISSUE THREAD

**Issue by Morinohtar** [realrashid/sweet-alert#31]
- Package Version: 1.1.1

- Laravel Version: 5.7.22

Firstly, good job with the package. Now to the tiny issue...

### Description:

SweetAlert2 latest version, 8.x, uses a slightly different way to execute the alert.

Your current version of SweetAlert2, 7.x, executes with:
```js
swal();
```

8.x version:
```js
Swal.fire();
```

I think you cannot pass the data through the constructor anymore.

**Comment by realrashid** [comment]
Yes,
I'm working on this.

**Comment by HDVinnie** [comment]
@realrashid any update on this?
