### ISSUE TITLE
How are you planning to keep js/sweetalert.all.js up-to-date?

### ISSUE THREAD

**Issue by limonte** [realrashid/sweet-alert#34]
Good day @realrashid and thank you for the good work :muscle: 

I'm the author of SweetAlert2 and I was pleasantly surprised when I found this package.

I added the link to it to our README: https://github.com/sweetalert2/sweetalert2#related-community-projects

What I was wondering is: how are you planning to keep `js/sweetalert.all.js` up-to-date? Doing it manually sounds like a bad idea because we're releasing patch and minor versions quite often.

Any ideas on how to automate that process?

**Comment by realrashid** [comment]
Hi @limonte,

It's in my mind when i received issue #31 so i feel it's not a good way that i am doing so i planned to make it optional or add cdn support.

Right now i am working on this adding ability to use cdn or use the default `` sweetalert.all.js``  that's come with this package.

Let me know how's the idea?

Thanks for your kinds words!

**Comment by limonte** [comment]
> Right now i am working on this adding ability to use cdn or use the default sweetalert.all.js that's come with this package.
> Let me know how's the idea?

LGTM, please notify me when you submit the related PR, thank you!
