### ISSUE TITLE
Not compatible with Laravel 5.1

### ISSUE THREAD

**Issue by Legoraccio** [realrashid/sweet-alert#36]
- Package Version: 1.1.2
- Laravel Version: 5.1

### Description:
In laravel 5.1 the "resource_path()" function is not defined. It was added to Laravel 5.2 and later.

### Steps To Reproduce:
Install on Laravel 5.1

**Comment by realrashid** [comment]
Hi @Legoraccio 
Right now this package only support 5.4.0|5.5.0|5.6.0|5.7.0|~5.8.0|~5.9.0 laravel versions.
I don't planned to add old versions support.
