### ISSUE TITLE
Session store not set on request.

### ISSUE THREAD

**Issue by Gravitana** [realrashid/sweet-alert#37]
- Package Version: 1.1.2
- Laravel Version: 5.8.15

### Description:
When I try to using the Middleware, Laravel displays error 

> Session store not set on request.

![2019-05-07_10-14-10](https://user-images.githubusercontent.com/12384351/57273549-a1f1a000-70b1-11e9-95be-1b0c1aef1bf3.png)
### Steps To Reproduce:
Add *RealRashid\SweetAlert\ToSweetAlert::class* into the *app/Http/Kernel.php*

**Comment by realrashid** [comment]
Hi @Gravitana 
Please share the `Kernel.php` `$middlewareGroups` section here.
If you added `RealRashid\SweetAlert\ToSweetAlert::class` like this so change this to `\RealRashid\SweetAlert\ToSweetAlert::class`
Then run `composer dump-autoload` .

**Comment by Gravitana** [comment]
It works. I made the mistake of adding to the "$middleware" instead of the "$middleware**Groups**"
