### ISSUE TITLE
Helpers responses

### ISSUE THREAD

**Issue by AngelinCalu** [realrashid/sweet-alert#38]
I am trying to achieve somethig similar to the functionality shown here, only simpler, using this package.
https://codepen.io/anon/pen/WBEVPw

I have found the helpers:
`showConfirmButton($btnText = 'Ok', $btnColor = '#3085d6')`
and
`showCancelButton($btnText = 'Cancel', $btnColor = '#aaa')`

but, how do I capture the response from the button's triggering? 

-----------------------------------------------------------------------------------------
* Version used (Laravel v5.8.10, sweetalert2@8.11.1)

**Comment by insology** [comment]
@AngelinCalu 
i solved using javascript before submitting the form as the traditional sweetalert2 way.
Maybe can helpful for you.

`$('.deleteForm').submit(function(e) {
    var form = this;
    e.preventDefault();
    Swal.fire({
    title: 'Are you sure?',
    text: "You won't be able to revert this!",
    type: 'warning',
    showCancelButton: true,
    confirmButtonColor: '#3085d6',
    cancelButtonColor: '#d33',
    confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
    
    if (result.value) {
        form.submit();
    }
    })
})`
