### ISSUE TITLE
Request: Allow config variables to be set. 

### ISSUE THREAD

**Issue by bgarrison25** [realrashid/sweet-alert#39]
So, I want to be able to make my sweet alert persistent but have the config "allowOutsideClick" to be true. I eventually determined that I could just do "removeTimer" but in the end there are a ridiculous amount of configuration option combinations and making a method for every single one could get VERY tedious. 

I suggest that you create a function called setConfig($key, $value) that simply allows people that know which config options exist to set them the way they want. Maybe even allow $options to be sent in to the constructor and sent to setDefaultConfig($options). 

Depending on which way you would rather go with it I don't mind putting in a pull request.

**Comment by realrashid** [comment]
Hello @bgarrison25 ,
Thanks for the suggestion.
I will implement this in coming version it will be release soon.

You will be achieve this in two ways.
example:
- First way.
```php
alert()->success('SuccessAlert','Lorem ipsum dolor sit amet.')->persistent(true,false)->allowOutsideClick();
``` 
- Second way.
```php
// in .env
SWEET_ALERT_ALLOW_OUTSIDE_CLICK=true
``` 
> This work for all persistent alert modal!

**Comment by bgarrison25** [comment]
Hey @realrashid. Maybe it would be better for it to be a setter so you don't have to create two different methods for setting it to true or false.

For example:

`alert()->success('SuccessAlert','Lorem ipsum dolor sit amet.')->persistent(true,false)->setAllowOutsideClick(true);`

Also, maybe you could have a config file where we could set the defaults ourselves (pointing to env variables of course). Its best practice to use config() in your code instead of env() since the config can be cached while the env cannot. 

Something like this:

```
[
    'default_config' => [
        'allow_outside_click' => true
    ]
]
```

**Comment by realrashid** [comment]
Yes there is config file i was just showing the way you will done that.
Because as laravel developer you don't like to touch the config file you need to set the vaule in .env.
