### ISSUE TITLE
Error when include view

### ISSUE THREAD

**Issue by ssheduardo** [realrashid/sweet-alert#4]
## Error view

When include the view by default, the system show error  -> View [alert] not found

![image](https://user-images.githubusercontent.com/1160138/38194130-ece4742e-3675-11e8-90c7-8bd7a1ed5027.png)

![image](https://user-images.githubusercontent.com/1160138/38194202-5e913e22-3676-11e8-82de-fffa39297711.png)

![image](https://user-images.githubusercontent.com/1160138/38194188-4d026e1a-3676-11e8-9a8e-b220bc8ce43d.png)

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Laravel 5.5 | sweetAlert2 - 1.1
* Ubuntu 16.04

**Comment by realrashid** [comment]
Hi,

May be its cache issue please run 
```
php artisan cache:clear
```
and 

```
composer dumpautoload 
```

readme have a little typo 

use this
``` js
<script src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js"></script>
```

instead of 

``` js 
<script src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js" />
```

Let me know if one of the above steps not work for you.

**Comment by ssheduardo** [comment]
Same error

![screenshot from 2018-04-02 17-42-16](https://user-images.githubusercontent.com/1160138/38202824-6867b1fc-369d-11e8-8e55-4a2b11b24de3.png)

![screenshot from 2018-04-02 17-44-28](https://user-images.githubusercontent.com/1160138/38202906-b3f39e2e-369d-11e8-95bb-99fe49f79455.png)

**Comment by realrashid** [comment]
Ok don't get why its doing..

run this 
```
php artisan vendor:publish --provider=RealRashid\SweetAlert\SweetAlertServiceProvider
```
artisan command to publish the view.

it will copy alert.blade.php in
resources/views/vendor/sweetalert/alert.blade.php

``` php 
@if (Session::has('alert.config'))
    <script>
        swal({!! Session::pull('alert.config') !!});
    </script>
@endif

```

**Comment by ssheduardo** [comment]
Not publish nothing

![screenshot from 2018-04-02 18-47-05](https://user-images.githubusercontent.com/1160138/38205296-676d0a28-36a6-11e8-92b7-0300270c41e8.png)

**Comment by realrashid** [comment]
Please share your package version from composer.json

**Comment by ssheduardo** [comment]
`"realrashid/sweet-alert": "^1.1",`

**Comment by realrashid** [comment]
Yes this is current version of package.

i think something wrong in your project 
make me wrong to create new project and install the package and fellow the instructions.

**Comment by ssheduardo** [comment]
A possibility solution is copy from file resources/views/vendor/sweetalert/alert.blade.php and paste in resources.

![image](https://user-images.githubusercontent.com/1160138/38247379-66341d8c-3745-11e8-9810-e7c6dda8a770.png)

Then call up the file manually.

![image](https://user-images.githubusercontent.com/1160138/38247396-7655eb82-3745-11e8-8ff8-8685dd62f356.png)

Thanks

**Comment by F4OST** [comment]
Hi,

So thanks to @ssheduardo it works but without exporting the vendor into ressources the plugin doesn't work :(

**Comment by F4OST** [comment]
It was working while I was using WAMP in localhost but did not work online on my host I don't know why.

If it actually did work for you with a new project I think it will be great to add a section **In case of error** in Readme where you can put the idea of @ssheduardo so people won't have to check issues to solve the problem.

**Comment by ssheduardo** [comment]
Of course, the idea is add the extra information when fail the install.
Sorry by my english

**Comment by realrashid** [comment]
Thanks @ssheduardo and @F4OST.

It was a little typo issue.

now finally the view issue is solved.

firstly run 
``` bash
composer update realrashid/sweet-alert
```
i missed double quotes in artisan command for publishing the alert view in above steps. 
``` bash
php artisan vendor:publish --provider="RealRashid\SweetAlert\SweetAlertServiceProvider"
``` 

What was the actual issue?

The issue was in folder name the first character in capital "V" but i used in ServiceProvider small "v" that's why the laravel view finder not getting that view.

now you can use this 
```
<script src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js"></script>
```
and include sweetalert view
```
@include('sweetalert::alert')
```
