### ISSUE TITLE
toast position using middleware

### ISSUE THREAD

**Issue by insology** [realrashid/sweet-alert#40]
- Package Version: #.#.#
"realrashid/sweet-alert": "^1.1"
- Laravel Version: #.#.#
"laravel/framework": "5.8.*"

### Description:
There is no a possibility to choose the toast position when i use the middleware, always is on bottom right.

return redirect('login')->with('toast_success', 'Login Successfully!');

**Comment by realrashid** [comment]
Hi @insology ,
Yes, in the current version you are not able to achieve this but in the coming version **v2.0** you will get some `.env` key to achieve this.

**Comment by insology** [comment]
Ok, good to know!
Thanks
