### ISSUE TITLE
Session errors (alert.config) returning only one error i.e. the last error

### ISSUE THREAD

**Issue by harshsiimteq** [realrashid/sweet-alert#41]
- Package Version: ^1.1
- Laravel Version: 5.8.*

### Description:
Session errors returning only one error

### Steps To Reproduce:
I have created one update form, in which there are 5 fields, all fields validations are taken care by laravel validator.
In my form 2 fields are unique, so I entered value which are already taken by other model, which means they were not unique, so I should get 2 error message for both field but I am getting only last one.

```PHP
@if ($errors->any())
      @foreach ($errors->all() as $error)
          @php
             toast($error, 'error', 'bottom-right')->autoClose(3000);
          @endphp
     @endforeach
@endif
```

These piece of code giving me only last error toast.

**Comment by realrashid** [comment]
Watch this https://youtu.be/bE8Err1twRw?t=482.
I will add some more methods for validation soon in feature release.

**Comment by realrashid** [comment]
Hey @harshsiimteq check out the docs.

**Comment by harshsiimteq** [comment]
Ok Thanks.
