### ISSUE TITLE
Class App\Http\RealRashid\SweetAlert\ToSweetAlert does not exist

### ISSUE THREAD

**Issue by madun** [realrashid/sweet-alert#42]
`RealRashid\SweetAlert\ToSweetAlert::class`

when i put this code into Karnel middlewaregroups i gota an error. What i missed?

i read this https://realrashid.github.io/sweet-alert/middleware?id=middleware

**Comment by realrashid** [comment]
Hi @madun 
```php
\RealRashid\SweetAlert\ToSweetAlert::class
```
Add like above!

**Comment by realrashid** [comment]
fix #42
