### ISSUE TITLE
sweetalert.all.js:1 Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by vin33t** [realrashid/sweet-alert#45]
- Package Version: 2.0
- Laravel Version: 5.8

### Description:
sweetalert.all.js:1 Uncaught TypeError: Cannot read property 'querySelector' of null
    at q (sweetalert.all.js:1)
    at H (sweetalert.all.js:1)
    at I (sweetalert.all.js:1)
    at rt (sweetalert.all.js:1)
    at sweetalert.all.js:1
    at ue._main (sweetalert.all.js:1)
    at new ue (sweetalert.all.js:1)
    at c (sweetalert.all.js:1)
    at Function.fire (sweetalert.all.js:1)
    at create:22

### Steps To Reproduce:
called from controller
        Alert::success('Success Title', 'Success Message');

**Comment by realrashid** [comment]
Hi @vin33t ,
Are you sure you install and configured properly?

**Comment by vin33t** [comment]
> Hi @vin33t ,
> Are you sure you install and configured properly?

yes, I did, twice on different projects

**Comment by edlobo98** [comment]
Hi @vin33t, the thing is that you should include @include('sweetalert::alert') inside the body tags of your document, I was having the same problem but I found that solution

**Comment by realrashid** [comment]
Hey @vin33t 
Do the right configuration follow the documents.

@edlobo98 thanks for your help.
