### ISSUE TITLE
Support for Laravel 6

### ISSUE THREAD

**Issue by fukuball** [realrashid/sweet-alert#46]
Please support for Laravel 6, thanks!

**Comment by abhishekdeshkar** [comment]
+1

**Comment by realrashid** [comment]
Soon you will get support for Laravel 6. 😎

**Comment by RhynelGIT** [comment]
me too https://stackoverflow.com/questions/57797295/cant-install-sweetalert2-in-laravel-6-0?noredirect=1#comment102032064_57797295

**Comment by RhynelGIT** [comment]
<3
