### ISSUE TITLE
too big in mobile version

### ISSUE THREAD

**Issue by retry19** [realrashid/sweet-alert#48]
- Package Version: #.#.#
- Laravel Version: #.#.#

### Description:
when i use Toast in desktop version is fine and look good, but if in mobile version it's too big

### Steps To Reproduce:

**Comment by realrashid** [comment]
Hey @retry19 
Set the default width in .env file.
```
/*
|--------------------------------------------------------------------------
| Width
|--------------------------------------------------------------------------
| Modal window width, including paddings (box-sizing: border-box).
| Can be in px or %.
| The default width is 32rem.
| This is for the all Modal windows.
| for particular modal just use the width() helper method.
*/
SWEET_ALERT_WIDTH=32rem
```

Or use the `width()` helper method.

```
// example:
toast('Post Updated','success','top-right')->width('100px');
```

But this will not do anything for the design responsiveness.

I will check this issue with sweetalert.

**Comment by retry19** [comment]
ok thanks, but how can i set width responsive?

**Comment by realrashid** [comment]
Please check out this sweetalert2/sweetalert2#272
