### ISSUE TITLE
Getting data from a sweetalert modal

### ISSUE THREAD

**Issue by HombreGeek** [realrashid/sweet-alert#5]
Thanx in advanced,

All I want to know Is it possible to open a sweetalert modal with  inputs and make a laravel validation, showing errors if they are, otherwise  saving data in the BD?

Have a nice day!

**Comment by realrashid** [comment]
Hello!
Yes this is possible with SweetAlert official Js Library.
But right now it not possible with this package.  

Soon i will add this too in this package.
