### ISSUE TITLE
Not Displayed proper alert message in the master file 

### ISSUE THREAD

**Issue by juwellmus** [realrashid/sweet-alert#51]
- Package Version: #.#.#
- Laravel Version: 6.0

### Description:
Alert gives proper output outside of the master file. 
But when using in the master file then it gives this 
[ https://user-images.githubusercontent.com/22576412/65787763-7e6fe480-e17b-11e9-9db9-35a6e4e09db4.png ] output.

### Steps To Reproduce:

**Comment by erickleinde** [comment]
Same problem here. Does anyone have a solution?

**Comment by realrashid** [comment]
Hello Guys 👋,
I am out of country right now so i can't make any fix but i recommend check your other JavaScript libraries and comment out one by one and you will get which one creating this problem 😉.

**Comment by erickleinde** [comment]
hey @realrashid 

my problem is, that the js and view is not included in my main view. i have follow the docs but it does not work 🤷‍♂

**Comment by erickleinde** [comment]
hey @realrashid 

I did that twice, but it does not work..

```php
public function store(Request $request)
    {

        $validation = $request->validate([
            'name'  => ['required', 'unique:groups,name'],
            'description'   => ['required'],
            'email'         => ['nullable', 'email']
        ]);

        try {
            $group = new Group();
            $group->name = $request->name;
            $group->description = $request->description;
            $group->email = $request->email;
            $group->save();
            Alert::toast(Lang::get('settings.groups.create.success'), 'success');
            return redirect(route('settings.groups.index'));
        } catch (\Exception $exception) {
            Alert::error(null, Lang::get('settings.groups.create.error'));
            return redirect(route('settings.groups.index'));
        }
    }
```
```html
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title') | {{ config('app.name') }}</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css">
    @yield('css')
</head>
<body>
<!-- SWEET ALERT -->
@include('sweetalert::alert')
<!-- SWEET ALERT -->
<!-- NAVIGATION BAR -->
@include('layout.topnav')
<!-- NAVIGATION BAR -->

<!-- CONTENT -->
<div class="container-fluid h-100">
    <div class="row h-100">
        <!-- SIDEBAR -->
        <div class="col-md-2 sidebar-wrapper">
            @include('layout.sidebar')
        </div>
        <!-- SIDEBAR -->
        <!-- CONTENT -->
        <div class="col-md-10 ml-auto content-wrapper">
            <section class="content">
                @yield('content')
            </section>
        </div>
        <!-- CONTENT -->
    </div>
</div>
<!-- CONTENT -->

<script src="{{ asset('js/app.js') }}"></script>
@yield('script')
</body>
</html>
```
and this is the output in google devtools
![image](https://user-images.githubusercontent.com/20875923/65907581-e6fdd200-e3c4-11e9-8218-b1a031dab35c.png)

**Comment by realrashid** [comment]
Hello @erickleinde ,
I have seen the output it's mean you didn't set the variables on .env file.
```php
// By Default its true 
// Turn it to false
SWEET_ALERT_LOCAL=true
// Add sweetalert2 cdn link
SWEET_ALERT_CDN=''
```

And last but not least please add the `@include('sweetalert::alert')` </body>.
Like this `@include('sweetalert::alert') </body>`

**Comment by realrashid** [comment]
Hello @erickleinde ,
I have seen the output it's mean you didn't set the variables on .env file.
```php
SWEET_ALERT_LOCAL=true
SWEET_ALERT_CDN=''
```

And last but not least please add the `@include('sweetalert::alert')` </body>.
Like this `@include('sweetalert::alert') </body>`

**Comment by erickleinde** [comment]
hey @realrashid 

I changed it, but it's still the same problem

**Comment by juwellmus** [comment]
Hey @realrashid 
After comment out ### <script src="{{asset("js/backend_js")}}/jquery.min.js"></script> this JavaScript file it's work fine.
But how can we fix this problem?

**Comment by juwellmus** [comment]
@hey @realrashid 
Thanks. 
After update **jquery.min.js** library it's work good.

**Comment by realrashid** [comment]
Great to hear that man! 

@erickleinde is your issue solve or not let me know then i will close the issue.
