### ISSUE TITLE
Call to undefined method RealRashid\SweetAlert\Toaster::add()

### ISSUE THREAD

**Issue by Shipu** [realrashid/sweet-alert#55]
- Package Version: 2.0.3
- Laravel Version: 6.4.1

### Description:
Call to undefined method RealRashid\SweetAlert\Toaster::add()

### Steps To Reproduce:
always show this 500 error

**Comment by realrashid** [comment]
close due to inactivity!

**Comment by kashifsindhu** [comment]
@if (alert()->ready())
        <script>
            swal({
                title: "{!! alert()->message() !!}",
                text: "{!! alert()->option('text') !!}",
                type: "{!! alert()->type() !!}",
                @if(alert()->option('timer'))
                timer: {!! alert()->option('timer') !!},
                showConfirmButton: false,
                @endif
            });
        </script>
    @endif

I got this Error .
 
Error
Call to undefined method RealRashid\SweetAlert\Toaster::ready()

**Comment by realrashid** [comment]
After installing the sweet-alert package, register the service provider

RealRashid\SweetAlert\SweetAlertServiceProvider::class,
Copy to clipboardErrorCopied
in your config/app.php configuration file:

'providers' => [
    /*
    * Package Service Providers...
    */
    RealRashid\SweetAlert\SweetAlertServiceProvider::class,
],
Copy to clipboardErrorCopied
Also, add the Alert facade to the aliases array in your app configuration
file:

'Alert' => RealRashid\SweetAlert\Facades\Alert::class,

**Comment by CarlAlaeddin** [comment]
After adding providers and aliases you need to go through the following steps

 first include the sweet alert under the script tag
`  @include('sweetalert::alert') `

publish the Sweet Alert file
`  php artisan sweetalert:publish  `
