### ISSUE TITLE
Sweetalert2 update to V9

### ISSUE THREAD

**Issue by paytrdev** [realrashid/sweet-alert#56]
- Package Version: 2.0.3
- Laravel Version: 6.5.0

### Description:
Sweetalert2 package update to version 9 and changed  'type' to 'icon' that's why server side sended alert icon dosn't work.
 please update this package ,thank you. 
### Steps To Reproduce:
https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0

**Comment by realrashid** [comment]
Hey @paytrdev ,
Yeah sure you will get update soon 😊👍.
