### ISSUE TITLE
Confirm before deletion

### ISSUE THREAD

**Issue by afrasiyabhaider** [realrashid/sweet-alert#57]
I am using Laravel 6.5 with sweet alert's 2.0.3 version

I want to know that, how to display the confirm button before the deletion of data?
If user press **yes delete it** it should be deleted otherwise it shouldn't be deleted

**Comment by realrashid** [comment]
Duplicate #17

**Comment by afrasiyabhaider** [comment]
Hey @realrashid how are you?
Did you added this feature in your new release?
If so then please let me know

**Comment by delvin20** [comment]
Hello @realrashid , have you added it?

**Comment by realrashid** [comment]
Hey,
Now i am free and i will give time to add this feature to this package. 🎉

**Comment by delvin20** [comment]
Thanks a lot @realrashid :)

**Comment by samlorlah** [comment]
@realrashid, well done. Please we still await this update. Regards

**Comment by afrasiyabhaider** [comment]
@realrashid bro is this feature will be available in next update?

**Comment by realrashid** [comment]
I still need to write some **dynamic** code to make this function flexible.
If you can share how you are doing in the moment this really help me to write simple helper functions.

Please Share to at realrashid05@gmail.com.

Thanks for your support. :heart:

**Comment by samuelhgf** [comment]
@realrashid Any news about this feature?

**Comment by erenergul** [comment]
I saw you closed it but Still wondering how do you handle delete confirmation ? I couldn't find any proper answer. we need to delete and confirm from controller ?

**Comment by nizartcht** [comment]
any new sugguestions to how to handled confirmation from the blade before sending the request to the controller

**Comment by realrashid** [comment]
Hey Guys..

Please checkout https://dev.to/realrashid/how-to-use-sweetalert2-with-livewire-56i6 this.

Thanks

**Comment by afrasiyabhaider** [comment]
In Live Wire there is a Custom coded JS confirmation box which can still be used in Blade component with Custom coding.... But can you please include it into your package so we dont have to use custom coding?

@realrashid

**Comment by syofyanzuhad** [comment]
guys, if you want to show confirm button before deleting a data in your blade file you can add this script:
```javascript
Swal.fire({
    title: 'Yakin ingin menghapus data?',
    text: "You won't be able to revert this !",
    icon: 'warning',
    showCancelButton: true,
    confirmButtonColor: '#3085d6',
    cancelButtonColor: '#d33',
    confirmButtonText: 'Yes, delete it!'
}).then((result) => {
    if (result.isConfirmed) {
        $(`[data-penguji=${id_penguji}]`).parents('.raised.card').remove()
    }
})
```

**Comment by hiprm** [comment]
any update?

**Comment by realrashid** [comment]
It's not added yet..

**Comment by Diverti** [comment]
> guys, if you want to show confirm button before deleting a data in your blade file you can add this script:
> 
> ```js
> Swal.fire({
>     title: 'Yakin ingin menghapus data?',
>     text: "You won't be able to revert this !",
>     icon: 'warning',
>     showCancelButton: true,
>     confirmButtonColor: '#3085d6',
>     cancelButtonColor: '#d33',
>     confirmButtonText: 'Yes, delete it!'
> }).then((result) => {
>     if (result.isConfirmed) {
>         $(`[data-penguji=${id_penguji}]`).parents('.raised.card').remove()
>     }
> })
> ```

That is not a good solution, because the Swal is not defined on the page is there was no other alert before.
This is only works with the SWEET_ALERT_ALWAYS_LOAD_JS=true .env variable.
