### ISSUE TITLE
Way to include SweetAlert JS on every page?

### ISSUE THREAD

**Issue by jacobgraf** [realrashid/sweet-alert#60]
Is there a way to force `@include('sweetalert::alert')` to include the js on every page? It appears it only loads it when I use the middleware or Facade. I have some outside JS that I'd like to use SweetAlert for, but your packages seems to only load the js when your package needs it.

Maybe I am missing something, but that's what it appears to be doing.

**Comment by realrashid** [comment]
Hello @jacobgraf ,

There's no way to do this in package level but in programmatically you can do.
Like below
Add an if statement in your layout or where you want to load the `sweetalert.all.js`
```php
@if (!Session::has('alert.config'))
    <script src="{{ asset('vendor/sweetalert/sweetalert.all.js')  }}"></script>
@endif
@include('sweetalert::alert')
```
The above condition checks if there's no session named alert.config so it will load `sweetalert.all.js`
but if it false it's mean the if statement found the session named alert.config then the `sweetalert.all.js` will load by `@include('sweetalert::alert')`.

Hope this help.

**Comment by jacobgraf** [comment]
Excellent work-around. Thanks!

**Comment by jacobgraf** [comment]
One other quick question, does `@include('sweetalert::alert')` do anything else except output `<script src="{{ asset('vendor/sweetalert/sweetalert.all.js')  }}"></script>`?

Is there a downside to simply using `<script src="{{ asset('vendor/sweetalert/sweetalert.all.js')  }}"></script>` and not even worrying about the `@include('sweetalert::alert')`?

**Comment by realrashid** [comment]
`@include('sweetalert::alert')`
It's required to show alert when you trigger alert() or toast() method from controller.

**Comment by jacobgraf** [comment]
Ok gottcha. Thanks again for the work-around.
