### ISSUE TITLE
QUESTION: calling SweetAlert using JS in Laravel

### ISSUE THREAD

**Issue by schonhose** [realrashid/sweet-alert#61]
## Detailed description
I use this package in my Laravel 6 setup and it works beautifully. I do have some JS in my project (mostly AJAX calls) and I want to give the user feedback through sweetalert. Using the documentation I used the following code:

`const Toast = Swal.mixin({
  toast: true,
  position: 'top-end',
  showConfirmButton: false,
  timer: 5000,
  timerProgressBar: true,
  onOpen: (toast) => {
    toast.addEventListener('mouseenter', Swal.stopTimer)
    toast.addEventListener('mouseleave', Swal.resumeTimer)
  }
});`

In the JS I call the Toast using:

`Toast.fire({
    icon: 'success',
    title: 'This is a success toast!'
});`

This code is based on the example found at the end of the Configuration segment over at [SweetAlert 2 readme](https://sweetalert2.github.io/#configuration).

The problem, however, is that the toast is displaying, but the icon (in the case of the provided example "success") is not shown. I suspect that the JS version does not know where the icons are, so that would explain the fact the icon is not showing.

So how can I point towards the location of the icon and have it shown in the Toast?

**Comment by schonhose** [comment]
Interestingly I just came about two javascript errors:

- Unknown parameter "TimerProgressBar"
- Unknown parameter "Icon"

**Comment by realrashid** [comment]
Hey @schonhose ,
```js 
const Toast = Swal.mixin({ toast: true, position: 'top-end', showConfirmButton: false, timer: 5000, timerProgressBar: true, onOpen: (toast) => { toast.addEventListener('mouseenter', Swal.stopTimer) toast.addEventListener('mouseleave', Swal.resumeTimer) } });
```
Where are you adding above code?

If you doing natively mean you are writing JavaScript code for sweetalert js so you must try this with CDN.
Like below

```sh
@include('sweetalert::alert', ['cdn' => "https://cdn.jsdelivr.net/npm/sweetalert2@9"])
```

**Comment by schonhose** [comment]
hey @realrashid,

I am adding the code in my JS file, which also contains the  JS code for the AJAX calls. In my project the sweetalert JS is loaded using your package. I will try your solution later tonight.

**Comment by schonhose** [comment]
I forgot to update the question, but trying the CDN as given in your comment, does not work. Despite pointing to a CDN the page still uses its local sweetalert.all.js.

Nevertheless I did manage to find out what the problem was. Old versions (<9) use the `type` declaration instead of the `icon`. So when I use the local sweetalert.all.js I need to use `type` to make it work.

See also: https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0

The second error I had regarding `timerProgressBar` is related to a new feature introduced in 9.30. See https://github.com/sweetalert2/sweetalert2/blob/master/CHANGELOG.md

So, the question is, when will you be able to update the local assets of the package?

**Comment by realrashid** [comment]
Hey @schonhose 
I have again tested with the above syntax this worked perfectly.
```php
@include('sweetalert::alert', ['cdn' => "https://cdn.jsdelivr.net/npm/sweetalert2@9"])
```
See the sweetalert.all.js pulled from it's cdn
![image](https://user-images.githubusercontent.com/15607685/71064674-75e2e500-2191-11ea-99e7-757fb3a1eb18.png)

The package local asset is already updated with sweetalert v9 in v3.0.0.
[Uptaded to SweetAlert2 V9](https://github.com/realrashid/sweet-alert/commit/e2f903dce6bd1be32c9e81ee1b80938613083a01)

This package not using `type` its using `icon`.

Let's come to your second error.
I will soon update the local asset with v9.5.3 and add the support for `timerProgressBar`.

**Comment by schonhose** [comment]
Ah, I probably forgot to publish the vendor files.

**Comment by realrashid** [comment]
close due to inactivity!
