### ISSUE TITLE
Icons not displaying in v3.0.1

### ISSUE THREAD

**Issue by afrasiyabhaider** [realrashid/sweet-alert#62]
After updating to v3.0.1 in Laravel 6.8 all (Success, Error, Info) icons are disappeared please help me to fix this issue @realrashid  

* Version used (e.g. Laravel v6.8, Package version 3.0.1):
* Operating system and version ( Windows 10):

**Comment by realrashid** [comment]
Hey @afrasiyabhaider ,

Please run the below command to publish the package assets.

```php
php artisan vendor:publish --provider="RealRashid\SweetAlert\SweetAlertServiceProvider"
```

**Comment by afrasiyabhaider** [comment]
It didn't worked

**Comment by realrashid** [comment]
Add the force flag.

```php
php artisan vendor:publish --provider="RealRashid\SweetAlert\SweetAlertServiceProvider" --force
```

**Comment by afrasiyabhaider** [comment]
Still Not working

**Comment by realrashid** [comment]
Hey @afrasiyabhaider ,
I am not getting why it's not working.

Please goto `public\vendor\sweetalert` delete the `sweetalert.all.js` then try again with below command.

```bash
php artisan vendor:publish --provider="RealRashid\SweetAlert\SweetAlertServiceProvider" --force
```

By the way i release a new version v3.1.0 [check it out](https://github.com/realrashid/sweet-alert/releases/tag/v3.1.0)

**Comment by afrasiyabhaider** [comment]
Solved Now
Thanks alot @realrashid 
and please develop a confirmation dialogue before deleting a record I am waiting for that feature
