### ISSUE TITLE
Middleware : all error messages displayed by default

### ISSUE THREAD

**Issue by Okipa** [realrashid/sweet-alert#64]
- Package Version: 3.1.0
- Laravel Version: 6.9.0

### Description:

When implementing the middleware, now all error messages are displayed by default in an alert message, and the package does not provides any way to avoid that if we do not want to trigger it.

For example, in my case, I've added a catch in the exception handler to display a simple `Invalid fields have been detected.` message, and I display each error message under the field in error (default behavior for bootstrap) : https://github.com/Okipa/starter/blob/master/app/Exceptions/Handler.php#L88

I agree that this feature can be very useful for users, but I think that it could be great to allow users to activate this or not from a config value, in order to let them choose.

### Steps To Reproduce:

Validate a form without filling a `required` field, with the middleware activated.

**Comment by Okipa** [comment]
@realrashid I've just submitted a PR for this : https://github.com/realrashid/sweet-alert/pull/65

**Comment by realrashid** [comment]
Fixed in v3.1.1.
