### ISSUE TITLE
Use with ajax

### ISSUE THREAD

**Issue by NanoCellWebDesign** [realrashid/sweet-alert#69]
using ajax for message alerts on page

How can i call this on an ajax request? i tried using  `Alert::alert('Title', 'Message', 'Type');` in the php function the ajax call but nothing happend

* Version used (e.g. Laravel v6.0, SweetAlert2 v3.1.0 - 2019-12-29):
* Operating system and version (Windows 10):

**Comment by realrashid** [comment]
Hey @NanoCellWebDesign this is the most requested feature but it's not implemented yet.
So I'm closing the issue but i will inform you when i implement it.
