### ISSUE TITLE
Prevent auto close sweet alert

### ISSUE THREAD

**Issue by namakutyo** [realrashid/sweet-alert#7]
swal({
  closeOnClickOutside: false,
});

not working/unknown
laravel 5.4

**Comment by realrashid** [comment]
Hi, You can do this using ``persistent()`` method
its take two parameters 

```php 
// boolean 
$showConfirmBtn = true; 
$showCloseBtn = false;
 ```
``` php
alert()->success('Alert Persistent', 'Successfully')->persistent(false,true);
```

you can get all [Chain Methods here!](https://github.com/realrashid/sweet-alert#chain-methods)
