### ISSUE TITLE
Nginx gateway error when adding helpers

### ISSUE THREAD

**Issue by snapey** [realrashid/sweet-alert#70]
Cautionary warning to others that have the same issue.

Stacking on helpers would create an Nginx 502 error.

The problem is caused by several versions of 6.x shipping with the session driver set to Cookie.  The problem with this is that the session is limited to 4k. When you extend the alert text, or stack on additional attribute via helpers then the error randomly appears.

The answer is to switch to file base sessions.

6.11 has reverted to file for session, but if you first installed your project with an affected version, then upgrading to later versions will not revert the entry in your config or .env

**Comment by realrashid** [comment]
Yes, you right that was the issue on Laravel but now the issue is fixed.
They set the SESSION_DRIVER=file again.
[Checkout this ](https://github.com/laravel/laravel/commit/eca7bc7d66cef63500a62e8deaa3fce1772f1641)

**Comment by snapey** [comment]
Yes I know (and said so earlier), but anyone that installed an affected 6.8, 6.9 or 6.10 release will NOT have it fixed by upgrade.
