### ISSUE TITLE
showConfirmButton is not working with me

### ISSUE THREAD

**Issue by greatsami** [realrashid/sweet-alert#71]
- Package Version: ^3.1
- Laravel Version: ^6.2

I'm trying to hide OK button by adding ->persistent(false, false) & ->showConfirmButton(false)
But it doesn't work.

What I should do to hide (OK button) when I don't need it?

**Comment by realrashid** [comment]
Hey @greatsami ,
If you want to hide the Confirm Button just use the `->persistent(false,false)`

```php
// example:
alert()->success('SuccessAlert','Lorem ipsum dolor sit amet.')->persistent(false,false);
```
The above example will hide the Confirm Button and Cancel Button too.

**Comment by greatsami** [comment]
Hi @realrashid 

I did it but it doesn't work.

Actually, I updated /vendor/realrashid/sweet-alert/src/Toaster.php

```
public function showConfirmButton($btnText = 'Ok', $btnColor = '#3085d6')
    {
        $this->config['showConfirmButton'] = $btnText != '' || $btnText != false ? true : false;
        $this->config['confirmButtonText'] = $btnText;
        $this->config['confirmButtonColor'] = $btnColor;
        $this->config['allowOutsideClick'] = $btnText != '' || $btnText != false ? true : false;
        // $this->removeTimer();

        $this->flash();
        return $this;
    }
```
Then I used like this:
```
alert()->success('Created successfully')->showConfirmButton(false)->timerProgressBar();
```

And it is worked with me.
