### ISSUE TITLE
multiple toast alerts?

### ISSUE THREAD

**Issue by mpixelz** [realrashid/sweet-alert#72]
Hi,
is there a way to show multiple toast alerts? i know it wasnt possible before but now we have toasts in the options so how can we have multiple alerts in toasts? 
p.s im pushing alerts from controller using Alert::toast();

**Comment by realrashid** [comment]
Hey @mpixelz ,
It's not possible to show multiple alerts or toasts on same page.
Because the package uses Laravel Session's so the alert or toast have same session keys name.
When you use `Alert::toast('','','')` this will generate sweetalert js code.

**Comment by realrashid** [comment]
Closed due inactivity.
