### ISSUE TITLE
There are no commands defined in the "sweetalert" namespace.

### ISSUE THREAD

**Issue by DhitiaCahya** [realrashid/sweet-alert#73]
i have followed the documentation then moved to configuration when i wanna run `php artisan sweetalert:publish` below message occured, how to solve the issue?

> There are no commands defined in the "sweetalert" namespace.

## Your environment
 "php": "^7.3",
        "laravel/framework": "6.9",
        "realrashid/sweet-alert": "^2.0",

**Comment by realrashid** [comment]
Hey @DhitiaCahya ,
Please update the package to v3.1.3 or use `php artisan vendor:publish --provider="RealRashid\SweetAlert\SweetAlertServiceProvider` command.

**Comment by realrashid** [comment]
Closed due inactivity.

**Comment by aeshareef** [comment]
There are no commands defined in the "sweetalert" namespace. laravel 9
