### ISSUE TITLE
How i can set custom classes to any element in the modal??

### ISSUE THREAD

**Issue by rajkinkhabwala** [realrashid/sweet-alert#74]
Title i is the only q. I want to ask!

**Comment by realrashid** [comment]
Hey @rajkinkhabwala ,
Can you tell me how you want to use these classes?
In the next version i am planning to add these classes to as `.env` variables but i am also thinking to add a method for specific modal if someone don't want to override the default classes on all modals.

**Comment by rajkinkhabwala** [comment]
ohh yes! we know that sweetalert2 has a customClass parameter in it func.!! so i would suggest to make function in Toaster.php file.
Like: 
`public function customclasses(array $classes){
$this->config['customClass'] = $classes;
$this->flash();
return $this;
}`
i made this function in my project and i was working perfectly!!
and you can also create object in the "setDefaultConfig" function too.
So by that way, you can add same thing to the sweetalert.php config file and in env file too.
