### ISSUE TITLE
Add support for Laravel 7

### ISSUE THREAD

**Issue by SupunSam** [realrashid/sweet-alert#75]
This package is not yet updated to the latest Laravel 7.

**Comment by realrashid** [comment]
Hey @SupunSam ,
This package have support for Laravel 7 [Please checkout](https://github.com/realrashid/sweet-alert/commit/b3854cc6e629948f13e8227f34b15e5deddf2933)

**Comment by SupunSam** [comment]
Hi @realrashid .. Yes, I got an error coz I haven't updated my composer JSON to the latest version. It had 2.0. I was under the impression that these packages will automatically update to the latest version with Composer update without changing the composer.json.
