### ISSUE TITLE
Add https://github.com/sweetalert2/sweetalert2 link to README

### ISSUE THREAD

**Issue by limonte** [realrashid/sweet-alert#76]
Good day, Rashid

Would you mind adding https://github.com/sweetalert2/sweetalert2 link to README?

It would be a fair sign of appreciation of the core dependency you're using :) The link to this project is in https://github.com/sweetalert2/sweetalert2#related-community-projects

**Comment by realrashid** [comment]
Yeah Sure!
I would love to 😊😉..
I also mentioned the library on credit section of documentation.

**Comment by limonte** [comment]
Thank you @realrashid :clap:
