### ISSUE TITLE
Message in blank

### ISSUE THREAD

**Issue by jezamba** [realrashid/sweet-alert#77]
- Package Version: "realrashid/sweet-alert": "^3.1"
- Laravel Version: "laravel/framework": "^7.0",

### Description:
every message that I try to send only show de image below

![error](https://user-images.githubusercontent.com/2524599/78585299-9baafd00-7807-11ea-9022-8045a7d8e106.png)
in the file ALERT.BLADE.PHP I must to delete the @if (Session::has('alert.config')) because not allow to show the message, but when the @if is deleted only show blanks popus

**Comment by realrashid** [comment]
Hey @jezamba ,
i suggest you to update the package to the latest version.
![image](https://user-images.githubusercontent.com/15607685/78587811-f881d400-7856-11ea-9c0b-bba3c3e61a9c.png)
The current version of package is **v3.148**

**Comment by jezamba** [comment]
You are right, after update the message appears with no problem
