### ISSUE TITLE
How To Use toast.addEventListener With Helper?

### ISSUE THREAD

**Issue by reasecret** [realrashid/sweet-alert#82]
We can stop toast timer in blade like this:
`
onOpen: (toast) => {
			    toast.addEventListener('mouseenter', Swal.stopTimer)
			    toast.addEventListener('mouseleave', Swal.resumeTimer)
			  }
`

How can I implement this to helper in my controller?

I'm using this code in my controller:
`toast('Profile updated','success')->timerProgressBar();`

**Comment by maicol07** [comment]
I think this is related to my feature request #85
