### ISSUE TITLE
Alert.config array empty after passing alert via a redirect.

### ISSUE THREAD

**Issue by adammpkins** [realrashid/sweet-alert#83]
- Package Version: 3.1.4
- Laravel Version: 7.9.2

### Description:
Alert.config array empty after passing alert via a redirect.

### Steps To Reproduce:
Called:
return redirect(route('home'))->with('success', 'Task Created Successfully!');

No alert fired, despite all config steps followed. 

After investigating, dumping session()->all() returns 
```
array:6 [▼
...
  "alert" => []
  "success" => "Task Created Successfully!"
]
```

**Comment by adammpkins** [comment]
Can add as a user on repo if necessary.

**Comment by realrashid** [comment]
Hey @adammpkins ,

Can you grant me access to your project?

**Comment by realrashid** [comment]
Hi,
Have you included the `\RealRashid\SweetAlert\ToSweetAlert::class,`?

And one more thing have you added `SWEET_ALERT_AUTO_DISPLAY_ERROR_MESSAGES` in your `.env` to turn `SWEET_ALERT_AUTO_DISPLAY_ERROR_MESSAGES=true` .

Set the `SWEET_ALERT_AUTO_DISPLAY_ERROR_MESSAGES`  `.env` value to true to activate the automatic displaying for the validation error messages.

**Comment by jpmurray** [comment]
I'm not sure if it's the same trouble, but I'll try not to open a new issue for it.

I'm also passing some alerts through redirects (ie.: `->with('success', "Bravo!");`). All of them works, except `error`.

This is working: `->with('info', "Here's some information");`
This is *not* working: `->with('error', "Sad trombone");`

**Comment by realrashid** [comment]
Hey @jpmurray ,
Maybe the error type have some issue.
Let me check it out

**Comment by realrashid** [comment]
Hey @jpmurray ,

I have run some test on the middleware part of the package.

The package work as excepted from my side.

![error middleware](https://user-images.githubusercontent.com/15607685/84381324-4b368e00-ac02-11ea-837d-f1746dcd3564.PNG)

**Comment by realrashid** [comment]
Hey @adammpkins ,

This is working: `->with('info', "Here's some information");`
This is not working: `->with('error', "Sad trombone");`

Because this is not `error` this is `errors`.

E.g  `->with('errors', "Sad trombone");` .

There was a type in docs.

Checkout the #91
