### ISSUE TITLE
Sweet Alert 2 is not working with Laravel 7

### ISSUE THREAD

**Issue by oluwatosinolamilekan** [realrashid/sweet-alert#84]
- Package Version: 3.1
- Laravel Version: 7

### Description:
![image](https://user-images.githubusercontent.com/29930457/82757920-4a68c400-9ddb-11ea-824f-1cb98d317ee1.png)

![image](https://user-images.githubusercontent.com/29930457/82757930-55235900-9ddb-11ea-9aaa-bc557d87c44b.png)

### Steps To Reproduce:

**Comment by realrashid** [comment]
Hey @oluwatosinolamilekan ,

Why not use the helper method `alert()->success ("","");` or change the ` use Alert;` to ` use RealRashid\SweetAlert\Facades\Alert;`

Let me know if it's not helpful.

**Comment by oluwatosinolamilekan** [comment]
same thing none of them work

**Comment by realrashid** [comment]
Hey @realrashid ,

Have you run `composer dump-autoload` ?

If is your project on github grant me access on your project then i will check what's wrong.

**Comment by realrashid** [comment]
Hey @oluwatosinolamilekan ,

I have just tried with Laravel 7 the package works smoothly.

```bash
realrashid@Rasho-PC MINGW64 /c/laragon/www/sweetalert-demo
$ pa
Laravel Framework 7.13.0
``` 
![worked](https://user-images.githubusercontent.com/15607685/83001651-7aa3a300-a025-11ea-981e-89b1c5ab4f82.PNG)

**Comment by jpmurray** [comment]
Just adding my voice to confirm, but I've just installed on Laravel 7.x and it works perfectly.
