### ISSUE TITLE
Alert or toast doesn't show up

### ISSUE THREAD

**Issue by maicol07** [realrashid/sweet-alert#86]
*   Package Version: 3.1.4
*   Laravel Version: 7.13.0

### Description:

When login fails, alert is not showing up

### Steps To Reproduce:

1.  Install Laravel Auth
2.  Override the `sendFailedLoginResponse` method in the login controller with this one:

```php
protected function sendFailedLoginResponse(Request $request)
 {
     return back()->with('toast_error', trans('auth.failed'));
 }
```
3. Try to register
4. Fail the login (wrong user/psw)

**Comment by realrashid** [comment]
Hey @maicol07 ,
Sad to heard about the issue.

Can you please tell the step have to you done?

Have you added `\RealRashid\SweetAlert\ToSweetAlert::class,` into the $middlewareGroups of your `app/Http/Kernel.php` file and also have you set the `SWEET_ALERT_AUTO_DISPLAY_ERROR_MESSAGES` variable to your .env file and value to be true to activate the automatic displaying for the validation error messages.

Let me know if the above step didn't helped you.

**Comment by maicol07** [comment]
I've solved some days ago but I've forgotten the fix :sweat\_smile: 

Anyway, this is solved
