### ISSUE TITLE
Return Redirect on Middleware not showing Error type

### ISSUE THREAD

**Issue by beesum** [realrashid/sweet-alert#89]
- Package Version: v3.1.5
- Laravel Version: v7.14.1

### Description:
After following the documentation, when returning/redirecting from middleware the error type does not show the sweetalert. I tried with types success, info, question and warning, they all work.

### Steps To Reproduce:
Setup middleware and add `->with('warning', 'Whoops!');` to the return or redirect.  It does not show the sweetalert.  Test again using `->with('info', 'Whoops!');` and it does work.

(Disclaimer, I am a new to php and laravel so I may be missing something)

**Comment by realrashid** [comment]
Hey @beesum ,
This is the second time I have heard about this issue ☹️.

But when i test out the about this issue everything seems good to me ☹️.

Is it possible for you to grant me access in your project to deep dive into the issue to what's wrong?😊

Looking forward to hearing back from you.😊

**Comment by realrashid** [comment]
The issue is closed due to inactivity.

**Comment by lordz123** [comment]
hi i have a same question , the error type ` return back()->with('errors', $validator->messages()->all()[0])->withInput();` not showing up
