### ISSUE TITLE
SweetAlert warning: "showConfirmButton" option has been deprecated. Please use "button" instead. More details: https://sweetalert.js.org/docs/#button

### ISSUE THREAD

**Issue by jangrimm** [realrashid/sweet-alert#9]
## Detailed description
I integrated everything successfully from the Git repository and got the entire thing to work and to show up. Great! However, only so far - things, such as icons (success or error) or buttons do not ordinarily work; they won't show up. The reason, as the JS console outputs, is reference to deprecated functions: 

https://i.imgur.com/hZkUaON.png

Errors (warnings):

- SweetAlert warning: "showConfirmButton" option has been deprecated. Please use "button" instead. More details: https://sweetalert.js.org/docs/#button
sweetalert.min.js:1:39674
- SweetAlert warning: "type" option has been deprecated. Please use "icon" instead. More details: https://sweetalert.js.org/docs/#icon
## Your environment
PHP7+, HTML5, CSS3, Laravel 5.6

**Comment by realrashid** [comment]
Hi,
This is because you are using wrong SweetAlert js library please use below one and let me know..
``` js 
<script src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js"></script>
```
official site [SweetAlert2](https://sweetalert2.github.io/)
