### ISSUE TITLE
Sweetalert not loading into view

### ISSUE THREAD

**Issue by DylanDec** [realrashid/sweet-alert#90]
Goodday

I just finished the 'install', 'configuration' and 'middleware' section of the documentation.

I have added `@include('sweetalert::alert')` to app.blade.php. When I open the dev console in chrome I don't get anything.

Kind Regards

* Latest version Laravel and SweetAlert
* Windows 10

**Comment by DylanDec** [comment]
Fixed it, thanks for your work.

**Comment by OscarTango1995** [comment]
how did you fix it i have the exact same issue
