### ISSUE TITLE
with('error') not working

### ISSUE THREAD

**Issue by hoRacy** [realrashid/sweet-alert#91]
- Package Version: 3.*
- Laravel Version: 7.*

There's a mistake in a documentation:
https://realrashid.github.io/sweet-alert/middleware?id=middleware

According to documentation:
return back()->with('error', 'Error Messagge');
should work, but not working.

Working version: 
return back()->with('errors', 'Error Messagge');

**Comment by realrashid** [comment]
Hey @hoRacy ,

Thank you for your correction.

There's was a type in documentation i will update soon.

Thank you 😊
