### ISSUE TITLE
Always or Never load sweet alert js package | Support for npm/utilizing the js package/livewire

### ISSUE THREAD

**Issue by farhanianz** [realrashid/sweet-alert#92]
For now this package has only support for providing a cdn instead of using the preloaded sweetalert.all.js bundled with the package. So, it's not possible (or it's cumbersome/repeating codes) to utilize npm/laravel-mix bundle. Even not possible to fire alert using swal.fire() unless I fired an alert using the facade/helper of `realrashid/sweet-alert`.

## Detailed description
The main goal is to utilize the sweetalert js package more conveniently.

There are situations where one might always/never want to load the sweet-alert.all.js bundled with your package. Currently I can define a cdn link but what if I want to pull the package from npm & use laravel-mix/webpack then just use the compiled app.js? 

## Context
As we already have `realrashid/sweet-alert` installed so we might want to utilize it, not by just facade/helper but also by using the swal.fire(). 

But looking through the codes & blade files of this package, I found out it only loads the js file if there is an alert/toast already fired/set, which is a good idea to reduce the requests count but there could be a better way.

I suggest adding more config variables like alwaysLoadJs & neverLoadJs and utilize it in alert.blade.php. And let the user decide what to do with the js package.

There will be no BC break. It'll be an improvement.

## Possible implementation

Currently I'm working on a project where I'm using the `livewire/livewire`, I tried to fire some alerts from livewire components but failed. So, I thought I can utilize livewire events & show the alert it using the swal.fire() manually. So, I'll need to have the sweetalert package loaded, which isn't there as I did not already have a alert set using realrashid/sweet-alert facade/helper.

So, If one can handle the sweetalert js part by thyself, then your package does not need to worry about it.

I'm willing to send a pull request.

**Comment by realrashid** [comment]
Fix in #93
