### ISSUE TITLE
Text or HTML (custom config) in Middleware Alerts

### ISSUE THREAD

**Issue by maicol07** [realrashid/sweet-alert#94]
## Detailed description
Add support for Text/HTML field in middleware alerts

## Context
Write some text instead of a long title

## Possible implementation
Instead of passing in the `with` method to the `value` parameter a string, you can change it to array. This way, custom configs of Alerts can be possible

## Your environment

* Version used (e.g. Laravel v5.6, SweetAlert2 v7.18.0): Laravel 7.21, SweetAlert2 3.1.6
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Windows 10

**Comment by realrashid** [comment]
Hey @maicol07 ,

There's are lots of environment variable for middleware alert.

But in sometime i will also add an option for convert the middleware text alert to html.
