### ISSUE TITLE
Please add the  Middle Option in the positioning of  toast 

### ISSUE THREAD

**Issue by cs-abdulwahab** [realrashid/sweet-alert#99]
- Package Version: #.#.#
- Laravel Version: 7.#.#

### Description:
Please add the  positioning of   middle    as  there are options for  start and end only

![toast sweet alert](https://user-images.githubusercontent.com/5089848/90467360-77ecb180-e12d-11ea-8582-e40d9d873364.png)

**Comment by realrashid** [comment]
Hey 👋,

You can add SWEET_ALERT_MIDDLEWARE_TOAST_POSITION
In your .env file as SWEET_ALERT_MIDDLEWARE_TOAST_POSITION="top-center" or
as you want.😎
